### ISSUE TITLE
Show total onboarded stations in explorer

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#10]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Website
- Android Application

### **Is your feature request related to a problem? Please describe.**
No

### **Describe the solution you'd like**
Explorer to show the total onboarded stations, so you don't have to count them.

### **Describe alternatives you've considered**
None

![Explorer showing stations onboarded](https://user-images.githubusercontent.com/46647866/155738726-add84d62-fcbb-43ce-a0f1-d79ecf87cb42.jpg)

**Comment by eeVoskos** [comment]
Thanks for the feature request. This is actually something we have under development - not to be expected very soon though. The explorer is currently very basic. We aim to make it the go-to global dashboard for the WeatherXM network stats, with more station + token info about the network as a whole.

**Comment by PavlosTze** [comment]
Implemented in our [Explorer](explorer.weatherxm.com)
