### ISSUE TITLE
Setting)clearing the friendly name from the station details page changes it in that page, but not on Detailed WXM Rewards page until navigating back to app home page

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#100]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
Setting or clearing the friendly name is done from the Station Details page, but the name change doesn't propagate throughout the app until navigating back to the home page.

### **How To Reproduce**
1. Go to Station Details page for a station without a friendly name. Use "Edit Name" to set a friendly station name. Notice the name change in the station details page.
2. immediately navigate to the "See Detailed WXM Rewards" page. Notice the friendly name doesn't display. It still displays the actual station name.
3. Navigate back to the home page. Notice the friendly name displays.
4. Drill back down through the station details page and the Detailed WXM Rewards page. Notice the friendly name now displays.
5. Go back to Station Details page for the same station. Use "Edit Name" to now clear the friendly station name. Notice the displayed name in the station details page reverts to the actual 3 word station name.
6. immediately navigate to the "See Detailed WXM Rewards" page. Notice the friendly name is still displayed.
7. Navigate back to the home page. Notice the actual 3 word station name displays.
8. Drill back down through the station details page and the Detailed WXM Rewards page. Notice the 3 word station name now displays.

### **Expected behavior**
When the friendly name is set, edited or cleared, the change should apply everywhere in the app without having to first revisit the app home page.

### **Screenshots**
N/A

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.2-f886e20

### **Additional context**
N/A

**Comment by Greg15** [comment]
A likely related bug... Changing temperature setting from the station details page (and probably any weather data setting) doesn't take effect after returning to the station details page until subsequently going to the home page and refreshing.

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Regarding the temperature setting issue, we will include the fix in a future version.

Thank you! :)
