### ISSUE TITLE
Swipe refresh in Historical Charts screen causing glitch.

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#102]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

Swipe down refresh on historical charts screen in android app is causing small glitch where the data momentarily displays different historical data, then refreshes.

### **How To Reproduce**
1. Go to Historical Charts 
2. Swipe down refresh.

### **Expected behavior**

Different historical data should not appear.

### **Screenshots**
Unable to take a screenshot but posted video of screen to Discord in Beta chat 

https://discord.com/channels/813503633278631946/910951496189902918/993969389470744647

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Google Pixel 2 
 - OS: Android 11
 - Android App Version. 3.1.2-f886e20 

### **Additional context**
    
Greg has a similar but slightly different issue, when swiping refresh, his screen displays and "oops no data" watermark, but his chart doesn't change as mine does.

https://discord.com/channels/813503633278631946/910951496189902918/993977966650462259

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
