### ISSUE TITLE
M5 battery-charge level indicator, if possible

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#103]
### WeatherXM Related Element
- M5 Firmware

### **Is your feature request related to a problem? Please describe.**
In certain onboarding, evaluation, demonstration or testing scenarios, the M5 unit is operated from battery for a while. For example, temporarily using an M5/wifi version to evaluate if a candidate deployment location would be a good deployment location for a helium version, and there is not wifi or electrical service at that location. In that evaluation scenario, a cell phone can be used as a hotspot, and the M5 can be configured to connect to the phone's wifi hotspot, and the phone's cellular connection can be used as the backhaul, all while the M5 runs on battery.
Similarly, an existing M5/wifi unit could even be used temporarily to evaluate if or demonstrate that a location is a good candidate for a permanent M5/unit deployment. The ability to do so and initially demonstrate the viability of the location without involving the people that control access to the building interior (for electric outlet) and roof and site's wifi (and needing them to share the WiFi credentials for the evaluation) could be useful. For instance if attempting to demonstrate to a business owner the value and viability of placing a unit on their business property and the value to enter into a hosting agreement. It could be done in the business's parking lot with an M5 and a cell phone and a station on a portable stand without accessing or disrupting the business's activity.

In these scenarios, there is no indicator if the M5 battery level is sufficient for the the evaluation/demonstration/testing period, or if the M5 battery is about to run out of charge.

### **Describe the solution you'd like**
The M5 may not even have the ability to monitor and report on its battery charge level, and the scenarios I listed may occur for very few people, but for anyone that might do something like the above scenarios, it would be awesome to have some battery charge-level indicator on the M5 screen, at least when operating solely on battery.

### **Describe alternatives you've considered**
If the M5 doesn't have the built-in ability to monitor battery charge level, but can at least determine if it's operating solely from battery, perhaps the M5 can display elapsed time since it went to battery-only mode.

### **Additional context**
N/A

**Comment by gkoumanos** [comment]
We close this as it is moved in the backlog for a feature to show if USB charger is plugged in or not and maybe 3-4 battery levels.
