### ISSUE TITLE
Newly onboarded station has not had opportunity to receive rewards yet, but app shows last reward happened 3 days ago, in the amount of zero wxm

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#104]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
This station was just onboarded today, around 10am (utc-5), and has never had opportunity to receive rewards yet. Rewards chart shows a date and time, although zero tokens for that date and time. Contextually, I thought that date/time was meant to indicate when this station last received rewards (although maybe it's meant to indicate the last time rewards were distributed for any stations). The info seems a little confusing. 

### **How To Reproduce**
1. Onboard a station
2. Same day, look at the rewards chart, similar to the screenshot below

### **Expected behavior**
I expect no date/time to display for this station's reward until the station has actually received rewards.

### **Screenshots**
![Screenshot_20220705-172334.png](https://user-images.githubusercontent.com/70354350/177428068-1953a2cb-d5a2-4683-af69-04953f404d0b.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.2-f886e20

### **Additional context**
This is not my first station. For administrative reasons, it made sense to onboard it to a different console account than my first console account, to eventually be able to clearly determine how many rewards or amount of income during an historical period of time are associated with which station. Both as part of edge case testing, and to quickly onboard for now, I intentionally chose to initially associate the same polygon wallet to this 2nd console account, until I can do some testing with the scenario and until I have time to create a separate polygon address and associate it with the second console account. As a result, the app (via the backend) might be finding and displaying the last distribution associated with the wallet, rather than finding the last distribution associated with that particular station.

**Comment by PavlosTze** [comment]
This is a known issue but low priority at the moment. We plan to address this on a future iteration on our rewarding process, as it doesn't affect rewards at the moment except from the visual part of them.
