### ISSUE TITLE
Inconsistent display format of no rewards at the 7D and 30D level vs the All level

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#105]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
When a station has never received any rewards, the rewards section on the station details page shows "0" for 7D and 30D reward totals, but "-" for the All total.

### **How To Reproduce**
1. Onboard a new station 
2. Navigate to station details page and look at the rewards section 
3. See behavior 

### **Expected behavior**
The display of no rewards should be consistent in all 3 counts. Either zero for all three, or a dash for all three.

### **Screenshots**
![Screenshot_20220705-184819.png](https://user-images.githubusercontent.com/70354350/177448894-943b4bbb-efd8-4d63-8ec6-cd632b8499e6.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.2-f886e20

### **Additional context**
N/A

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
