### ISSUE TITLE
"All" WXM rewards total on rewards chart/tile did not initially update 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#106]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
After initial rewards were received, the 7D and 30D properly displayed on the rewards tile, but the "All" total on the rewards tile initially still showed a "-". After navigating in the app (maybe back to home page?) and returning to the station details page, the All total properly refreshed, as shown in the additional screenshot 7 minutes after the first.

### **How To Reproduce**
1. See screenshots 

### **Expected behavior**
When reward amounts update, they should all update at the same time

### **Screenshots**
![Screenshot_20220706-092639.png](https://user-images.githubusercontent.com/70354350/177578289-5831d081-1ddf-48fa-9912-c58c27d82420.png)
![Screenshot_20220706-093312.png](https://user-images.githubusercontent.com/70354350/177578318-c4a8090c-ad6f-48f1-834c-769e458d3d69.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.2-f886e20

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
