### ISSUE TITLE
Rounding of rewards are inconsistent between 7D/30D vs total on rewards tile

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#107]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
On the rewards chart/tile, the All amount is rounded differently than the 7D/30D amount

### **How To Reproduce**
1. See screenshot

### **Expected behavior**
A consistent rounding should be used everywhere.

### **Screenshots**
![Screenshot_20220706-092834.png](https://user-images.githubusercontent.com/70354350/177580424-d21df854-c41e-4496-a48c-3804ec41e62b.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.2-f886e20

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)

**Comment by Greg15** [comment]
@PavlosTze 
This issue is not resolved. Here are 2 units that have been on-boarded for less than 30 days. In that scenario, the 30 day total should match the All total. For one station, the 30 day total is higher than the All total. For the other the 30 day total is less than the All total.
![Screenshot_20220722-220545.png](https://user-images.githubusercontent.com/70354350/180588388-3722b947-a75f-44cb-abdd-7522f8d80746.png)
![Screenshot_20220722-220432.png](https://user-images.githubusercontent.com/70354350/180588392-7ae9e92d-1b36-4631-9ccc-ba64d41492f0.png)

**Comment by PavlosTze** [comment]
@Greg15 We will have a look at it again in the future. We will probably consider a different solution here, but it's a low priority atm.
