### ISSUE TITLE
Catch-up rewards algorithm appears incorrect, likely applying most recent day's data and resulting reward scale to prior missing days calculations rather than using data (or lack of data) from that day

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#108]
## WeatherXM Related Element
- Android Application (backend, But displays in app)

## **Describe the bug**
The example station only on-boarded yesterday, partly through the day, so in normal circumstances, today it should receive partial rewards for just yesterday. And in total, up to this point, should ONLY have received rewards for yesterday. Instead, the station received rewards for all of the days that other stations were missing rewards, utilizing this station's reward scale from yesterday's data. This inappropriately dilutes other stations' rewards on those earlier days. This possibly also means that other stations that had a reward scale from yesterday's data of less than 1 but should have had a reward scale on the missing days of 1 (based on actual weather data from those missing reward data) might have received reduced rewards on the catch up transactions even though they should have received full rewards in the catch up transactions. Conversely, a station with a reward scale of 1 yesterday that had lower reward scales during the makeup reward period would have been over-rewarded.

### **How To Reproduce**
1. See screenshot for example station that was only onboard for less than 1 day

### **Expected behavior**
Reward transactions should eventually result in the exact same amount of rewards for a given station, whether the reward distribution happens on the normal schedule or are delayed

### **Screenshots**
![Screenshot_20220706-102351.png](https://user-images.githubusercontent.com/70354350/177601025-2c788941-6766-4e88-a444-230d4a5efbb5.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - not relevant

### **Additional context**
None

**Comment by Greg15** [comment]
I found evidence that the makeup rewards were also incorrect for stations that were onboard throughout the entire period for which rewards were delayed. For the station in the attached picture, all three reward transactions done on July 6 (which I think we're for July 3, July 4 and July 5?) show a reward scale of 0.96, and a reward amount of 27.91. That corresponds to providing data for only 23 out of 24 hours. However, a look at the historical weather charts show that for only a single day was an hour of data missing. That hour was July 4, 10pm (notice there are only 2 data points to the right of the 8pm x-axis label on that day). For all other days, all 24 hours have data (notice there are all 3 data points to the right of the 8pm x-axis label for all other days than July 4).
So only 1 day's worth of transactions on July 6 should have had a reward scale of  0.96 and reduced rewards of 27.91. The other transactions on that day should have had a reward scale of 1, and been for a reward amount of 29.07

![Screenshot_20220707-230700.png](https://user-images.githubusercontent.com/70354350/177916352-0d1bc253-4721-4702-ac21-f1fe07162784.png)
![Screenshot_20220707-230945.png](https://user-images.githubusercontent.com/70354350/177916373-f411febc-4aff-4054-adcb-5141a38d0415.png)
![Screenshot_20220707-230823.png](https://user-images.githubusercontent.com/70354350/177916391-edadf98c-9776-4c9a-a48b-d848785b1343.png)
![Screenshot_20220707-230844.png](https://user-images.githubusercontent.com/70354350/177916409-0e591651-f39b-4b41-959e-6cf276cf6e6c.png)
![Screenshot_20220707-231002.png](https://user-images.githubusercontent.com/70354350/177916419-6332f4ab-677e-4350-a62e-dc429c073093.png)

**Comment by tmavroeid** [comment]
We are looking into this one in order to resolve it in our next release. Thank you for your feedback.
