### ISSUE TITLE
No tokens 

### ISSUE THREAD

**Issue by Knobba** [WeatherXM/issue-tracker#109]
I have received no rewards since the weekend about 5 days ago 
My m5 unit is in sync and connected to the internet with all green icons 
My miner is called brief Spruce rainstorm

**Comment by PavlosTze** [comment]
Where is it located? Have you input a wallet address? Can you please share some in-app screenshots?

**Comment by Knobba** [comment]
Restarted the m5 unit see if that makes a difference
