### ISSUE TITLE
Very extreme false precipitation readings 

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#110]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Weather Station or M5

## **Describe the bug**

**Smooth Pastel Degrees**

At 10:44am Pacific time during a sunny day, station reported **3244.6 mm/hr** precipitation to the M5 and app. After inspection, no debris or any malfunction seemed to be occurring with the rain cup. I wiped away some normal residue, moved the rain cup up and down, it seemed to return to it's position normally.

At 10:53am Pacific, after inspection, M5 and app display then read 7.6 mm/hr precipitation, rain icon remained on the app under current weather, and then at 11:06am pacific, 22 mins later,, station correctly began reporting 0.0 mm/hr precipitation.

Historical weather shows 600 mm of precipitation incorrectly.

### **How To Reproduce**
1. Go to historical charts for Smooth Pastel Degrees.
2. July 12, 2022 - first noticed at 10:44 am Pacific
3. See incorrect precipitation readings.

### **Expected behavior**

No extreme incorrect readings.

### **Screenshots**

![Screenshot_20220712-104805~2.png](https://user-images.githubusercontent.com/100298772/178567646-250e8f6f-ea99-4cab-91e7-8688069207e9.png)

![Screenshot_20220712-105939.png](https://user-images.githubusercontent.com/100298772/178567873-5d7f7721-9221-48a0-b635-d18f189dc0ec.png)

![Screenshot_20220712-110953.png](https://user-images.githubusercontent.com/100298772/178567909-8b8aca11-2428-474f-a172-bee9b05447cb.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: [Google Pixel 2
 - OS: [android 11
 
 - Android App Version  3.1.2-f886e20

**Comment by NikosTsiligaridis** [comment]
Looks like your weather station intermittently submits 0 values for some of the parameters, I'm investigating whether this is a weather station malfunction or bug.
