### ISSUE TITLE
New Explorer - Can't move the map vertically when zoomed out

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#114]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
On iPhone web browser, if you zoom all the way out in the new Explorer it will only allow the map to move horizontally, not vertically. You have to zoom in to get any horizontal map movement back.

### **How To Reproduce**
1. Go to https://weatherxm.com/explorer/
2. Zoom all the way out 
4. Try and move the map up and down 

### **Expected behavior**
The map can move in any direction at any zoom level.

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.6 
 - Browser Safari & Chrome

### **Additional context**
This also happens the same on a PC web browser, but that makes sense when zoomed all the way out, it just doesn't make sense on the mobile version.

**Comment by PavlosTze** [comment]
@RevNotDev We fixed this. This URL should redirect at https://explorer.weatherxm.com , please confirm that the redirection takes place now (maybe a clearing the cache is needed) so I can close the issue.

**Comment by RevNotDev** [comment]
All working fine now thanks 👍🏻
