### ISSUE TITLE
Web app stops updating, won't load station information

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#116]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
-Web App

## **Describe the bug**
When clicking/tapping on a station, sometimes the web app will not load the station information anymore. The blue loading bar at the top will fill all the way but the station page doesn't load. Also refreshing the devices list also doesn't work anymore when this happens. To get everything working and refreshing again, if you go into your profile, then go back to devices and click on a station it will then load the station information page properly and the device list will also refresh again.

### **How To Reproduce**
1. Go to https://app.weatherxm.com/devices
2. Click on a station, if it loads up, go back to the devices list and leave the page for a while (not sure how long for this issue to start)
3. Try clicking on a station again until the station information page doesn't load up. You will then see you can't refresh the device list anymore either.
4. Click on profile, then back to devices, now click on a station and the station information page will now load and the devices list will start refreshing again.

### **Expected behavior**
Station information pages to always load when clicked on and the devices list to always be refreshable.

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.6
 - Browser: Safari

**Comment by PavlosTze** [comment]
@RevNotDev We just released a new version that fixes this. Can you please confirm?

**Comment by RevNotDev** [comment]
Sure, will have to leave the web app open for a while. I'll keep checking periodically to see if the issue persists or not.

**Comment by RevNotDev** [comment]
Hasn't happened up to now and I think it normally would have by now if the issue was still there. Seems fixed to me 👍🏻

**Comment by PavlosTze** [comment]
Great to hear that! Thanks Rev!
