### ISSUE TITLE
Historical Charts don't allow you to scroll through the days until after selecting a day

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#117]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Web App

## **Describe the bug**
In the web app from my phone, after first navigating to the historical charts, the horizontal list of days is missing the ability to scroll left/right through the days until you click on a day. Because the list of days is left justified initially, this also means that it's not obvious that the initial displayed charts are for today. After clicking on a day, the charts change to the selected day AND the ability to scroll left/right to select other days appears.

### **How To Reproduce**
1. Go to historical charts
2. Notice that today's data is displayed, but the list of days is left justified, so the label of "Today" on the far right is not visible. Notice that there is no ability to scroll left/right through the days.
3. Click on one of the visible days.
4. Notice that when the charts update for the selected day, that the ability to scroll left/right through the days now appears 

### **Expected behavior**
When the historical charts first display, it should be obvious that the displayed chart is for today, and the ability to scroll left/right through the days should be available without first needing to select a day.

### **Screenshots**
![Screenshot_20220803-091039.png](https://user-images.githubusercontent.com/70354350/182633667-f78043a2-b29d-4d98-9dde-163603821431.png)
![Screenshot_20220803-091244.png](https://user-images.githubusercontent.com/70354350/182633726-840d80e2-e464-4128-9616-242341cdb93c.png)
![Screenshot_20220803-091330.png](https://user-images.githubusercontent.com/70354350/182633774-d8caf3dc-87aa-452c-9783-c5d6495dbd56.png)
![Screenshot_20220803-091343.png](https://user-images.githubusercontent.com/70354350/182633823-e8f689fe-793a-4f50-8069-f56acb7e552e.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: moto g7 power 
 - OS: Android version 10 
 - Browser: Chrome 103.0.5060.71

### **Additional context**
I confirmed behavior is same when using default rendering on my phone in the android version of Chrome, and when telling the android version of Chrome to render as Desktop Site

**Comment by PavlosTze** [comment]
This got fixed in the latest release. Thank you :)
