### ISSUE TITLE
switching wifi networks

### ISSUE THREAD

**Issue by aquaticpanda** [WeatherXM/issue-tracker#118]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- M5 Firmware

## **Describe the bug**
m5 was unable to join a wifi network it had previously joined

### **How To Reproduce**
swiped right on m5
clicked configure wifi
entered password for previsouly used wifi network. password is accepted.
m5 does not actually connect to network stays offline. 
clicked configure wifi again and joined new wifi network. password accepted. m5 shows back online. 

I had a network outage and swapped m5 to hotspot. it connected without issue. When original network was restored I tried to switch back and could not get m5 back online. was not able to rejoin hotspot again. added m5 to secondary wifi network without issue and m5 came up right away. 

I have a second station and replicated the issue. both stations are up and online now.

### **Expected behavior**
expected to rejoin previous wifi network. 

### **If Applicable: Desktop (please complete the following information):**
 - Version [e.g. 3.0.0]

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iphone 12
 - OS: 14 I think? recently updated
 - Android App Version [e.g. 3.0.0], you can find it on the in-app Settings

### **If Applicable: M5 (please complete the following information):**
 - Firmware Version 0.3.11

**Comment by gkoumanos** [comment]
@aquaticpanda M5 does not store more than one WiFi network.
When you select "Configure WiFi" current WiFi is deleted the moment you press "Yes" to the "Configure WiFi" prompt, even if you don't complete the process to enter SSID/pass.
Keeping these in mind could you please rerun the steps?

**Comment by aquaticpanda** [comment]
fixed now. When I tried to switch back I was not able to. I hard reset my router to clear all DHCP leases and it came up so it looks like my switch was not releasing the IP of the M5 when I switched networks and switched back and that somehow was effecting the connection. Both units are on netgear nighthawk routers.

**Comment by gkoumanos** [comment]
That's great. Thanks for getting back to us.
