### ISSUE TITLE
[explorer.weatherxm.com] - Zoom indicators misplaced

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#12]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
In mobile version of the explore.weatherxm.com the screen doesn't take consideration of the upper part of the browser (see attached photos) and zoom in/out is out of focus. If you scroll the screen they're visible. You can only scroll the whole screen by touching part of the zoom button

### **How To Reproduce**
1. Go to explore.weatherxm.con

### **Expected behavior**
Be in focus. 

### **Screenshots**

![Screenshot_2022-02-25-17-57-20-064_com.android.chrome.jpg](https://user-images.githubusercontent.com/100304233/155746618-3bb4e72d-20f8-425e-9d0b-0ebf9fa9ca3e.jpg)

![Screenshot_2022-02-25-17-57-22-716_com.android.chrome.jpg](https://user-images.githubusercontent.com/100304233/155746706-1fa187e4-fdcc-4c9f-ac00-76e311e5115f.jpg)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Xiaomi Mi 10 Pro
 - OS: [Android 11]
 - Browser chrome
 - Android App Version [e.g. 3.0.0], you can find it on the in-app Settings

**Comment by PavlosTze** [comment]
Hello, this is fixed. We decided to remove these buttons entirely to mimic the Android's app explorer.
