### ISSUE TITLE
Total Rewards called different things in different parts of the app

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#121]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The all-time total rewards are called Total on the app homepage, but are called All on the station details page.

### **How To Reproduce**
1. Compare the 2 pages 

### **Expected behavior**
Normally, I would expect the same value to be called the same thing each time it is displayed.
Caveat: I do recognize that the word "Total" makes a lot of sense in the home page by itself. And I recognize that the station details page shows 3 totals, so the word Total doesn't quite work there (7D total, 30D total, and All total).
So, to make them consistent, the word All would be needed on the home page instead of the word Total on the station details page. If UX feedback is that All doesn't work contextually on the homepage, then ignore this bug report, but I at least wanted to point it out in case the I consistency hadn't been noticed.

### **Screenshots**
None needed

### **Smartphone (please complete the following information that are needed for this bug):**
 - Device: moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.5-902c130

### **Additional context**
I assume similar changes should be considered for web app, etc

**Comment by PavlosTze** [comment]
We decided to change the word "ALL" to "TOTAL" in the token card. A new redesign of this card will come in the future that will fix these issues and make it more clear and user friendly.

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this.
Thank you! :)
