### ISSUE TITLE
Historical Charts sometimes has "Today" listed twice 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#122]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The list of days at the top of the historic charts screen sometimes has Today listed twice.
I don't have much more info about when it happens, but user reported that it happened once before. The bug was reported in discord by Mr_Fuzzer. They opted not to submit the bug in GitHub because they didn't want to create a GitHub account, so I'm at least posting the screenshot so the team is aware and can possibly follow up with the user. The user posted the image at 8:10am localtime in Aug 10, and the user is UTC-5. Time of other occurrence is unknown.

From the timestamp on the downloaded file, it looks like user took the screenshot at 8:10am localtime on August 10, so the right most "Today" would have been Aug 10, and the left "Today" could have been Aug 9, and the day labeled "Yesterday" could have been Aug 8, because the next day is listed as Sun Aug 7. So I am guessing that the two days are using the label of "Today", but that the actual data is from 2 different days.

### **How To Reproduce**
1. Go to the the historical weather data page during the right conditions. Not sure what the right conditions are.

### **Expected behavior**
Today should only be listed once, and the day listed before "Yesterday" should be 2 days prior to today, not 3 days prior.

### **Screenshots**
![Screenshot_20220810_081015_WeatherXM.jpg](https://user-images.githubusercontent.com/70354350/184157227-46d21ba5-40af-4410-af86-e0b629fce7d3.jpg)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: unknown 
 - OS: unknown
 - Android App Version: unknown

### **Additional context**
 Edit: user confirms "If I rmemever correctly, the right most today was that day, so the 10th. The next today was yesterday, so Aug 9th. And I don't rememever opening yesterday so I can't say what It would load up, yesterday data or 2d ago data."

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
