### ISSUE TITLE
30D rewards chart is showing 31 days of bars

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#123]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The 30D rewards chart is showing 31 days of bars

### **How To Reproduce**
1. Go to station details page
2. Find the rewards chart. Notice that the default 7D chart shows 7 days in the chart.
3. Click on the 30D button. Notice that the 30D chart is showing 31 days in the chart.

### **Expected behavior**
A chart labeled 30D should show 30 days in the chart, not 31 days.

### **Screenshots**
![Screenshot_20220811-120827.png](https://user-images.githubusercontent.com/70354350/184194135-10e84343-5805-4521-ba4a-6089b788f250.png)

### **Smartphone:**
 - Device: moto g7 power 
 - OS: android version 10
 - Android App Version: 3.1.5-902c130

### **Additional context**
I have a vague memory of counting the bars in the 30D chart a long time ago when that feature was first released, and thought that I counted 30 days then, so this might be a more recently introduced bug.

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. We decided to go with 29 past days + today = 30 days. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
