### ISSUE TITLE
2 M5 units getting data from the same weather station show different current weather icons

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#125]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
As part of isolating some m5 self-reboot and freeze issues before remote deployment, I ended up having two m5 units receive data from the exact same weather station. However, the current weather icon in the app differed for each claimed device for a while.  One unit used the partly cloudy icon, while the other was showing a raining icon. I didn't watch it continuously, but it still differed 2 hours later, and I think the discrepancy persisted during the entire 2 hours. There seems to be something off in the logic for the current weather icon if 2 m5 units are getting the same weather data but displaying different current weather icons, and if it lasts longer than a boundary condition when weather transitions. In the screenshots shown, it shows the discrepancy at 2 snapshots 2 hours apart, so this doesn't appear to be a weather boundary/transition situation. In real life, once I'm done trying to capture some self-reboot and/or freeze behavior, there won't be 2 M5's connected to the same weather station. So, the real issue is that the current weather icon in the app doesn't seem to be reliably based on the actual weather station data (with or without combination of local forecast data). If it were reliably based on that, then both devices in the app would show the same current weather icon, so this seems to reveal a possible bug with the current weather icon logic.

### **How To Reproduce**
1. Power on a single weather station 
2. Turn on 2 M5's right next to each other 
3. Ensure both M5's connect to and display the same weather station ID
4. Monitor the android app until both claimed units start displaying different current weather icons. The data from the 2 units from the screenshots did this on 27 Aug 2022 between at least 9:56am and 11:59am, UTC-5.

### **Expected behavior**
The current weather data icon should be identical for the same weather station and GPS coordinates.

### **Screenshots**
![Screenshot_20220827-095639.png](https://user-images.githubusercontent.com/70354350/187057698-cee4de86-ccf6-425d-ac81-f5b603a4fbb1.png)
![Screenshot_20220827-115913.png](https://user-images.githubusercontent.com/70354350/187057702-78fd10d9-27ef-41e5-a469-e5f058edea73.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version: 3.1.6-8f2bb6f

### **Additional context**
None

**Comment by NikosTsiligaridis** [comment]
This is fixed in the upcoming 0.3.28 firmware (after losing connection to weather station #1, M5 doesn't look for any weather station to connect to, but to the one paired earlier).
