### ISSUE TITLE
Detailed WXM Rewards list in Android app not showing the transaction for Aug 23

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#126]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
The Detailed WXM Rewards list in the android app is not showing an entry for Aug 23 2022 even though the polygon explorer shows a transaction occurred that day. I checked 3 stations, and the issue exists for all 3 stations.
Recumbent Tangelo Weather
Best Coconut Altitude
Furry Golden Downpour
I also added up the rewards over the last 30 days as shown in that list for the first 2 of them, and the sum is missing roughly one days worth of rewards compared to the 30D total shown in the chart on the corresponding station details page, so the API seems to be including that day's rewards in the 30 day total shown in the graph, so it appears to be an issue isolated to just the list of detailed transactions.

### **How To Reproduce**
1. Go to Detailed WXM Rewards, and scroll back to Aug 22 to Aug 24 2022 range
2. Notice the absence of an entry for Aug 23
3. Go to the Polygon blockchain explorer and confirm that an entry actually exists on the blockchain

### **Expected behavior**
All transactions should appear in the detailed list

### **Screenshots**
![Screenshot_20220902-133419.png](https://user-images.githubusercontent.com/70354350/188217779-cd90406f-e39d-4112-b611-a7ecb1a499fd.png)

### **Smartphone**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.6-8f2bb6f

### **Additional context**
The same wallet address currently has all 3 stations associated with it. I confirmed using the blockchain explorer that the wallet address received 3 transactions that day, so it appears that each station received a reward that day. None of the stations show a transaction for that day in the detailed transactions list in the app.

**Comment by Greg15** [comment]
Additional Information:
I checked one day later. Instead of 23 August 2022 not showing in the Detailed WXM Rewards list, it's now 24 August. It's the same for all 3 devices. So now it is appearing as if it is the reward 10 days in the past that is the transaction that is not showing, rather than it being something specific to 23 August.

Also, the 30D charts properly show rewards those days. It appears that it is only the Detailed WXM Rewards list that is missing the transaction.
![Screenshot_20220903-232516.png](https://user-images.githubusercontent.com/70354350/188297477-392858a1-3966-43ed-8d06-7ac711860446.png)

**Comment by Greg15** [comment]
It's now in a new day again localtime, and now the missing day in the detailed transactions list has changed again to 25 August, so this definitely looks like the missing record is always 10 days ago.
![Screenshot_20220904-081850.png](https://user-images.githubusercontent.com/70354350/188315683-fb9eea54-ab80-41ac-858e-74fd5e2ed912.png)

**Comment by PavlosTze** [comment]
We just released a new API version which fixes this issue. Can you please confirm? Thank you :)

**Comment by Greg15** [comment]
Confirmed as fixed. Thanks.
