### ISSUE TITLE
Change red icons on M5 to also include an indicator that works for color blind people

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#127]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- M5 Firmware

### **Is your feature request related to a problem? Please describe.**
I was explaining a deployment to a host, and they pointed out that they are color blind for certain colors, so red and some shades of green look the same. As such, they couldn't really tell the difference between red and green icons on the M5. That will make it more difficult to work with the host to resolve issues when the station appears offline in the app. 

### **Describe the solution you'd like**
If the red icons could have an additional visual indicator, in addition to color, to indicate that there is a problem, it would help for this subset of people.
Just one example would be adding an "X" over the icon, although there are many ways to accomplish it.
Another way to think about it is have the red icons also change shape to indicate when there is an issue, such as would be done if the M5 only had a black and white display (also such as is done in the top row of an Android phone for no cell network connection, etc, because that top row on an Android phone doesn't use color)

### **Describe alternatives you've considered**
A configuration on the M5 to specify how to indicate working or not working, but that doesn't seem ideal

### **Additional context**
Currently, it's useful to be able to ask someone who has an issue "are all 3 icons green?". Additionally, there is already a feature request to make it more obvious on the M5 display when a connection to a weather station is or is not established, so that a support question could be "are all 4 icons green?".
Any change to those icons to make them also work for color blind people would ideally be consistent, so that a similar simple question could be asked of color blind people... "Do/Are all 3 (or 4) icons in the upper right <common attribute when working>?", or, "Do any of the 3 (or 4) icons in the upper right have <common visual attribute when not working>?".

**Comment by NikosTsiligaridis** [comment]
Hi
We will definitely implement something like this. Either an additional indicator or a different color scheme.

**Comment by NikosTsiligaridis** [comment]
@whippleslap This is also planned for the "about" screen. Will be released along with a new UI.
