### ISSUE TITLE
Detailed WXM Rewards list only shows approximately last 3 months 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#128]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
Back on 12 May 2022, the app appeared to only show approximately 30 or 31 days of transactions. Discussions in discord on that day indicated that the list was supposed to be infinite (at least for a while). The issue was handled without an actual GitHub submission, and the shown list length in the app was increased (and I thought it was increased to infinite). It's possible it was only increased to 3 months or so, or it may be possible it was changed to infinite at the time and then later reverted back to a finite list of approximately 3 months. At the time, there were more than 30 days of transactions, but not yet 3 months of transactions, so it would have been hard to confirm by an end user what the actual change was at that time. Now that there are more than 3 months of transactions for some stations, it's become clear that the list of detailed WXM rewards is not an infinite scroll. If the app is really supposed to support an infinite list of detailed WXM transactions, then the current behavior is a bug. If the app is really only supposed to support the display of the last 3 months or so, then another method needs to exist to retrieve historical rewards per station, since the current blockchain transactions do not indicate station. There are scenarios in which the station owner and/or host needs to know rewards per device (amount and datetime), and not just rewards per wallet.

### **How To Reproduce**
1. Launch the WXM Android app for an account that has a device that has been on-boarded and providing weather data for longer than 3 months.
2. Go to the Detailed WXM Rewards
3. Scroll down until no more scrolling is allowed
4. Notice that the list always stops scrolling at approximately 3 months.

### **Expected behavior**
The full rewards history per device needs to be available somehow/somewhere, whether in the app and/or by a different method (such as blockchain transactions). If in the app, then the detailed rewards list should support an infinite list.

### **Screenshots**
N/A

### **Smartphone**
 - Device: Moto g7 power 
 - OS: Android version 10 
 - Android App Version 3.1.6-8f2bb6f

### **Additional context**
Even if the Detailed WXM Rewards list is made infinite, it is still ***highly*** valuable for the info to also be available on-chain to allow support for reward reporting by device for any prior timeframe (e.g., prior calendar month, prior calendar quarter, calendar/fiscal year-to-date, prior calendar/fiscal year, etc), for precise valuation of each reward at the exact date and time of the reward, and for shared visibility between device owners and hosts, when applicable (where one owner might own multiple devices but have them deployed across multiple hosts).

**Comment by PavlosTze** [comment]
We just released a new API version which fixes this issue. Can you please confirm? Thank you :)

**Comment by Greg15** [comment]
Fixed
