### ISSUE TITLE
App home page "last seen" times are inaccurate and outdated when clicking back from station detail page

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#129]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
When clicking back and forth between home page and a station detail page, it becomes hard to know which conflicting data is more current.
The home page can claim it's more current, but the claim can be incorrect. For instance (as shown in the pics), at 2:05pm, the app home page can say the station was last seen 4 minutes ago, but that was when the page last rendered with refreshed data. So the displayed info is really from ~14 minutes ago, from ~1:51pm. From there, when I click on the station tile to go into the station details page, the station details page very briefly displays the data starting with the home page data (telling me the data is 14 minutes old), but quickly refreshes to updated data, showing me newer data from 1:59pm, and telling me it's data from 6 minutes ago.
Here is where the problem arises...
I click the back button in the app. The home page displays again, but displays the data from 1:51pm again, and also says it's from 4 minutes ago, even though it's outdated info from 14 minutes ago. So I click back into the station details page. Very briefly, the initial data on the station details page again is seeded with the outdated info from the homepage, and also says it's 14 minutes old, before updating to the newest data and updated 6 minutes ago. And again clicking the back button in the app returns to the home page with outdated info from >=14 minutes ago that still claims it's from 4 minutes ago.
Currently, the user has to infer that the home page data "from 4 minutes ago" is inaccurate and is actually older than the station details page data "from 6 minutes ago", and has to know to pull down from the top of the home page to refresh the home page.

### **How To Reproduce**
1. Go to app home page. Refresh the page. Ideally during a period where the heat is rising very quickly, so that outdated temperature readings are obvious
2. Let enough time pass for at least 1 new reading to be sent from the device to the WXM network. An ideal wait is 10 minutes, which will likely allow time for 2 additional readings to be sent.
3. Notice the "X minutes ago" on the home page is out of date, and note the temperature.
4. Click on a station tile, to navigate to the station details page.
5. Notice that very briefly the station details page will display the old temperature from the home page, as well as the actual time of that temperature reading, as well as an accurate count of how many "X minutes ago" that time really was. (Home page might say it was 4 minutes ago, but at this point it is really about 14 minutes ago, and will briefly show as 14 minutes ago on the station details page).
6. Notice the station details page will very quickly update to show newer temperature reading, along with the actual newer time of that reading, and along with an accurate count of how many minutes ago it was. In particular, note that under certain circumstances, the "X minutes ago" on the station details page can actually be a larger number of minutes ago than the "X minutes ago" on the home page, even though the absolute time of the corresponding data on the station details page is newer.
7. Click the back button in the app, to go to the app home page.
8. Notice that the temperature and "X minutes ago" display on the home page as if the home page had never been left. The refreshed data from the station details page does not propagate to the home page.
9. Click on station tile again.
10. Notice that step 6 repeats. The old data is again initially shown on the station details page.
11. Navigate back and forth several times between the station details page and the home page. Notice that the home page data and its "X minutes ago" never refreshes to reflect the updated data and timestamp from the station details page unless the user manually refreshes the home page by pulling down on the home page screen.

### **Expected behavior**
Data refreshes from the station details page should propagate to the home page.

### **Screenshots**
![Screenshot_20220905-140535.png](https://user-images.githubusercontent.com/70354350/188506428-07c84946-f91c-4ff6-94e0-9a8a5eb72985.png)
![Screenshot_20220905-140617.png](https://user-images.githubusercontent.com/70354350/188506436-cd69aa5c-c918-440d-abdf-eb9cea38d87b.png)

### **Smartphone:**
 - Device: Moto g7 power 
 - OS: android version 10 ]
 - Android App Version: 3.1.6-8f2bb6f

### **Additional context**
When addressing this issue, please consider the scenario where the home page has more than 1 station.
If the only home page station data that updates when a station details page is refreshed is the single station corresponding to that station details page, then the other stations on the home page will still incorrectly claim their data is only from, for example, "3 minutes ago", even if the data is from 20 minutes ago.

As a result, I'm wondering if the best solution is that whenever the app back button is used to navigate from the station details page back to the home page, if the entire home page should refresh its data. If so, can the phone back button event also be detected on that page transition, to chase a home page data refresh?

**Comment by PavlosTze** [comment]
Thank you for that @Greg15 , we are aware of that issue and we are already working on a solution where every time someone visits the details screen of a device or the devices list the data will be updated.

Also we will (probably) include a 1 minute polling on the device details screen.

Hopefully this will be fixed in the next release of our app.

**Comment by PavlosTze** [comment]
Fixed in the latest beta release. :)
