### ISSUE TITLE
Zooming bug on Explorer on iOS

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#13]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
The + and - for zooming are hidden by the address bar. When you tap on a station they appear at the top, but then are hidden again at the bottom when you tap out of the station. 

### **How To Reproduce**
1. Go to explorer.WeatherXM.com
2. See the icons for zooming are hidden.
3. Tap on any hex then any station and the zoom icons will appear at the top of the screen.
4. Tap out of the station and they will be hidden again at the bottom of the screen. 

### **Expected behavior**
The + and - zoom icons to never be hidden 

### **Screenshots**

![image](https://user-images.githubusercontent.com/46647866/155749143-8d3fbc06-2e30-4199-a67b-d58d0f9f99c4.png)
![image](https://user-images.githubusercontent.com/46647866/155749161-28190279-c06a-4530-8a6d-29e9c6410f87.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.3.1
 - Browser: Stock - Safari

**Comment by lynadi** [comment]
Fixed 
![Image from iOS (3)](https://user-images.githubusercontent.com/100237898/155977144-9dd380bb-d484-42fb-9fd5-8f8c6445e518.jpg)

**Comment by PavlosTze** [comment]
Hello, this is fixed. We decided to remove these buttons entirely to mimic the Android's app explorer.
