### ISSUE TITLE
Logic difference between web explorer and in-app explorer around "x minutes ago" and offline status 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#131]
## WeatherXM Related Element
- Website (web explorer)
- Android Application (in-app explorer)

## **Describe the bug**
Issue #130 revealed an additional issue, which I'm documenting in this submission.
Both the web explorer and android in-app explorer change a station's status to Offline when approximately 10 minutes have passed since data from the station was last believed to have been received. However, there is a small logic difference between the web explorer and the in-app explorer. The 2 sources should be consistent. In the web explorer, it takes 20 seconds or so for the web explorer to change a station's status to offline after "10 minutes ago" is reached, but a station changes to offline in the android in-app explorer immediately as (or right before) "10 minutes ago" is reached.
So either the logic for Offline status is different, or the logic to round/truncate to display "10 minutes ago" is different.

### **How To Reproduce**
1. Go to web explorer, and select a hex to get a station list for that hex.
2. Constantly refresh the page until a station changes to "10 minutes ago".
3. Start counting seconds, while continuing to constantly refresh the page. Count until the station status changes from online to offline. Notice that it took approximately 20 seconds to change to offline after "10 minutes ago was reached"
4. Go to in-app explorer in the android app, and select a hex to get a station list for that hex.
5. Constantly refresh the station list until a station changes to "10 minutes ago". (Refresh the station list by swiping down on the list to dismiss it, then click on the hex again to display the list again).
6. Notice that the station status changed to Offline either the last refresh as "9 minutes ago" or the first refresh as "10 minutes ago".

### **Expected behavior**
Both versions of the explorer should use identical logic for elapsed time and online/offline determination.

### **Screenshots**
N/A

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power
 - OS: android version 10
 - Browser: Chrome 105.0.5195.77
  - Android App Version: 3.1.6-8f2bb6f

### **Additional context**
If appropriate, read issue 130 that revealed this issue, in case the resolution of the 2 issues should be coordinated.

**Comment by PavlosTze** [comment]
We have found the issue at #130 and we have worked into a fix @Greg15 . Our backend was responsible for this as that's what clients (like the web-app and the mobile app) use to get the "last seen" data and the "online/offline" data. All platforms use the same source at this point of time.

Therefore there isn't an issue here that's why I have added a `wontfix` label as fixing #130 will probably fix this also.

Thank you :)
