### ISSUE TITLE
error between application and station

### ISSUE THREAD

**Issue by Dasti2** [WeatherXM/issue-tracker#134]
Hello, I have the station installed over a week and already three times I have turned off the first time for 57 minutes, first I thought that the power supply was damaged so I replaced it in a few days, it turned off again for 9 hours in both cases, when I touched the panel, it turned on itself, today It turned off again, but the screen was ok, all the signs were green and the phone showed off for 11 minutes, I turned off the application on the android phone and after a few minutes everything

**Comment by PavlosTze** [comment]
Please re-open the bug report following the default template.
