### ISSUE TITLE
Duplicated reward transaction

### ISSUE THREAD

**Issue by pratcheth** [WeatherXM/issue-tracker#136]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Blockchain transactions

## **Describe the bug**
There are two devices on one account. On the app I get rewards as they should be, but on the wallet they were doubled. So I checked the polygonscan and there are total of four transactions for the last 24 hours. 

### **Expected behavior**
There should be only two transactions, one per device.

### **Screenshots**
![trans](https://user-images.githubusercontent.com/1858291/193415748-528d5e51-f5ff-439f-b8cf-10e3c486f309.PNG)

### **Additional context**
[Link to Polygonscan](https://mumbai.polygonscan.com/token/0xecbbbf304fdf91cddda6c6643ed1300a552b691a?a=0xA436f621D6b33999597c86CF8c4758ca98f8A8BD)

**Comment by tmavroeid** [comment]
Thank you for the feedback! We have already addressed this issue. In the next hours, the amount of WXM distributed in Mumbai will match the one which is displayed in the mobile app.
