### ISSUE TITLE
Blockchain rewards for 2 October not appearing in App

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#138]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
On UTC 2 October, the actual blockchain reward transactions have properly returned to a single transaction per station. BUT, 1 hour and 13 minutes after the time of the "Transfer Multiple" blockchain transaction, the 7D/30D rewards chart in the station details page still does not show the rewards.

### **How To Reproduce**
1. Go to this URL to confirm the wallet for a particular station received rewards on UTC 2 October: https://mumbai.polygonscan.com/tx/0xbfba3d8ee56aeb8b81002a7facfe8e917d8d9229012b313b1583434380583f80

2. Launch the android app for that same station and confirm that the app doesn't show the rewards sent in the blockchain on 2 October. Stations with the issue include Recumbent Tangelo Weather, and Best Coconut Altitude.

### **Expected behavior**
The rewards in the app and blockchain Rewards should match.

### **Screenshots**
The blockchain rewards for both stations 
![Screenshot_20221002-012629.png](https://user-images.githubusercontent.com/70354350/193441131-5de7e666-6a95-4c22-af55-4ef2ef2abfd7.png)

The app screen
![Screenshot_20221002-012718.png](https://user-images.githubusercontent.com/70354350/193441156-9211f839-efcd-4ea8-b62c-83cec047bdd9.png)
![Screenshot_20221002-012739.png](https://user-images.githubusercontent.com/70354350/193441161-7f96f0fb-164a-469c-b1e0-88fb56769fe4.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.8-f5b5956

### **Additional context**
 None

**Comment by Greg15** [comment]
The issue has repeated for 3 October 2022

**Comment by tmavroeid** [comment]
Thank you for your feedback. That has happened due to testing of some new features that we added in our rewarding mechanism. The amount of WXM already rewarded in Mumbai will match the amount which is displayed in the mobile app in the next  hours.
