### ISSUE TITLE
Add Android App widget that shows current temp, current weather icon, and an icon for push notifications

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#139]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Android Application

### **Is your feature request related to a problem? Please describe.**
The longer I use the app, the more often I find I want to get the most basic recent info with the least steps possible. I suspect that the current temp, the current weather icon, and any indication of push notifications are the 3 most basic pieces of info wanted/needed in a widget without launching the app (in the absence of push notifications, online/offline status would take its place as a basic needed piece of info)

### **Describe the solution you'd like**
A small widget available for the WeatherXM Android app, that will show the most commonly checked things which I believe are current weather icon, current temp, and push notification indicator (or online/offline indicator). Then, the user can additionally launch the app if they want the wonderful full information.
Since the app account can have more than station associated with it, I propose that the widget allow a way to rotate through the stations. If that is not feasible, perhaps allow the user to mark one station as the default stations, and the widget uses that station. In that scenario, in the  absence of a station being marked as default, the widget uses the same logic that the app uses to identify which station to list first on the app homepage.

### **Describe alternatives you've considered**
None

### **Additional context**
I recognize it's not a high priority, but wanted to document this request now, because I genuinely would check the hyper-localized temp and weather icon more if it was a widget, rather than having to launch the app to do so.

**Comment by PavlosTze** [comment]
Thanks for the suggestion @Greg15. We plan to implement this in the future as we have already added it in our backlog by internal suggestions. :)
