### ISSUE TITLE
Altitude set-up and display

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#14]
### WeatherXM Related Element

- M5 Firmware
- Weather Station

### **Is your feature request related to a problem? Please describe.**
Initialize should also include weathers station altitude. 

### **Describe the solution you'd like**
The miner's GPS antenna should be on the lower part of the weather station or on the roof and import pole high to have event better localized data

**Comment by PavlosTze** [comment]
Thank you for your suggestion. Unfortunately this cannot be implemented in the current weather stations & miners. We are already considering a future weather station that will have an integrated GPS so that this suggestion will be therefore implemented there.
