### ISSUE TITLE
Web explorer does not display 7D and 30D reward totals

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#140]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
The web explorer shows zeros for the 7D and 30D totals (the android in-app explorer correctly shows the actual 7D and 30D Rewards total)

### **How To Reproduce**
1. Go to web explorer 
2. Click on any hex with a station 
3. Click on a station in the station list pop-up
4. Notice the 7D and 30D totals are zero, even when the graph itself shows rewards.

### **Expected behavior**
The 7D and 30D reward totals should be the accurate rewards received in those time periods.

### **Screenshots**
![Screenshot_20221010-093351.png](https://user-images.githubusercontent.com/70354350/194922060-f7f69768-0688-4b04-a682-b667e0840edb.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Browser Chrome

### **Additional context**
A new explorer version was released today. I cleared history/cookies for last 7 days.
I accessed the web explorer (explorer.weatherxm.com) using an android phone, with Chrome browser.

**Comment by PavlosTze** [comment]
Fixed :)
