### ISSUE TITLE
Temp data point pop-up in historical weather charts incorrect when Fahrenheit used 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#141]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The popups for single data points are incorrect in the temperature chart of the historical weather data when the setting is Fahrenheit. It is correct though when the setting is Celsius.

### **How To Reproduce**
1. Change settings in app to Fahrenheit 
2. Go to historical weather charts
3. Select a single data point in the temperature chart to get the pop-up telling the specific temperature and feels like temperature 
4. See the temperature being wrong, and not matching the y-axis range

### **Expected behavior**
The data point pop-up should be accurate

### **Screenshots**
Screenshot showing wrong Temperature with Fahrenheit
![Screenshot_20221011-071245.png](https://user-images.githubusercontent.com/70354350/195090738-b15173b0-ec14-49f1-b3eb-ef5fd00b3e11.png)

Screenshot showing correct temperature with Celsius 
![Screenshot_20221011-071443.png](https://user-images.githubusercontent.com/70354350/195090766-0ed3d7b4-eb53-45ca-8363-b4e9937e40d1.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.9-587f823

### **Additional context**
It appears the graph is correctly converting Celsius to Fahrenheit (24.4°C to 75.9°F) for the actual data point compared to the y-axis labels, but it looks like the data in the pop-up is taking the fahrenheit value in the chart and treating it like a Celsius number and trying to convert it again to Fahrenheit (75.9°F, but acting like 75.9°C * 9/5 +32 = 168.6°F)

**Comment by PavlosTze** [comment]
Thank you @Greg15 ! Fixed on the latest beta release :)
