### ISSUE TITLE
Historical weather data charts for Today display incorrectly when there are breaks in the data

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#142]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
2 issues happened when I intentionally took a station offline for 2 hours to test how the new  graphs work. After bringing the unit back online, the x-axis for the temperature chart for "Today" no longer shows all 24 hours. And, when there is only a single resumed data point for a secondary curve (such as wind gust and likely "feels like" temperature), it doesn't appear in the graph (but the value can be identified by clicking on the x-axis point, and seeing the value in the data point popup). This seems to be because the secondary lines do not contain actual "dots", just lines.

### **How To Reproduce**
1. Disable weather data transmission of an M5 for at least an entire clock hour in the middle of the day (changing the M5 frequency is an easy way to do this)
2. Re-enable transmission 
3. Go to app and refresh until the station shows online and shows current weather data again. transmission 
4. Navigate to historical weather data charts, and make sure "Today" is displayed. Notice the issues with how the temperature chart and the wind chart display.

### **Expected behavior**
The x-axis scale for the temperature chart should be 24 hour range. The wind gust should also be displayed in the graph.

### **Screenshots**
![Screenshot_20221011-140349.png](https://user-images.githubusercontent.com/70354350/195179060-88693ddc-7b9c-456e-89bd-768e74a708fe.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.9-587f823

### **Additional context**
None

**Comment by Greg15** [comment]
It turns out the non-displayed data point for a secondary line (one that currently doesn't have a dot or other indicator for each point on the line) is an issue anytime there is a standalone data point. This can happen the first hour data point after a station comes back online, but also happens for the first hour after midnight local time.
See these screenshots that show that the wind gust doesn't display on the chart when the time is between midnight and 1am localtime, even though it is a significant gust speed.

![Screenshot_20221013-001300.png](https://user-images.githubusercontent.com/70354350/195508611-c0747f23-9d7f-47e1-bb2e-3c5373ba91d3.png)
![Screenshot_20221013-001346.png](https://user-images.githubusercontent.com/70354350/195508629-49f7b98b-9fd1-4795-8bf0-b01f4626812a.png)

**Comment by PavlosTze** [comment]
This issue has been fixed in the latest beta version that has just been released. Thank you :)

**Comment by Greg15** [comment]
Tried to test it, by checking just after midnight. Unfortunately, the feels like temperature is same as ambient temperature, and the wind speed and wind gust are both 0.0, so I have to wait to test again another day, when the secondary data point is different from the primary data point, to see if the secondary data point properly appears.
