### ISSUE TITLE
Reward Scale and historical weather data charts do not match

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#143]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
This bug occurred with the unit Best Coconut Altitude.

I took it offline on purpose on 11 October for more than a full hour to test the new graph behavior. The entire missing hour was the noon (to 1pm) local time hour (UTC-5) (actual missing time would have been approximately 11:58am to 1:55pm localtime). The weather data graphs do show that hour gap for the noon hour in the charts as expected. And, the reward scale for the rewards sent on 12 October for the 11 October reward day is 0.96, which corresponds to a single hour missing out of the 24 hours. So far, things match.
But when I look at the historical weather data charts for 11 October, it also shows all data missing for all hours after 4pm local time. Since the UTC day starts at 7pm localtime for me, if data for those hours really wasn't provided to the WXM network, then the additional missing hours of 5pm and 6pm should have lowered my reward score to 0.88.

For a couple of reasons, I suspect that the reward scale is correct, and that my unit actually did send data to the WXM network from 5pm through midnight local time, and it just isn't displaying in the historical graphs, but either way, there is a discrepancy between the reward score and the amount of data shown in the graphs.

### **How To Reproduce**
1. In a UTC-5 timezone, disable the M5 from sending data for the noon hour, by changing the M5 frequency to the wrong frequency shortly before noon local time.
2. After 1pm localtime, re-enable the M5 by switching the frequency back to correct frequency.
3. Wait until just after 1am local time the next day and after the rewards are sent for the prior UTC day (which are done shortly after midnight local time in UTC-5 timezone).
4.  Check the Rewards Scale and notice it reflects only 1 hour of missing data, but check the historical weather data charts for the prior day, and notice the additional apparent missing weather data for the prior UTC day (up through 7pm localtime).

### **Expected behavior**
Rewards Scale and historical weather data charts should match. In this case, I suspect the weather data exists and just isn't being rendered. If so, the expected behavior is that all available weather data should display.

### **Screenshots**
![Screenshot_20221012-011503.png](https://user-images.githubusercontent.com/70354350/195270881-0e726f54-7229-43e1-b44e-c1e35c77e60e.png)
![Screenshot_20221012-013342.png](https://user-images.githubusercontent.com/70354350/195270929-7dcada1d-fb42-4d71-b1ec-9f718c23435e.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.9-587f823

### **Additional context**
None

**Comment by PavlosTze** [comment]
@Greg15 When you were at the first state of the historical charts missing the weather data after 4pm, have you tried swiping down to refresh it?

This definitely looks like a caching issue or something.

**Comment by Greg15** [comment]
I believe I did eventually, and maybe that's when it fixed. I can't remember if I did it earlier and it didn't help. If I have time to attempt to reproduce it, I'll try, but I'm swamped right now with some approaching deadlines.

**Comment by Greg15** [comment]
@PavlosTze I had a reason to check a different station, and encountered the issue again. The issue doesn't seem to be connected to disabling a station for over an hour yesterday.

On the additional station, clicking on Yesterday in the historical charts showed only data through 4pm yesterday or so (although I think the x-axis was for all 24 hours). A pull-down refresh does then reveal all 24 hours of data for yesterday.

I also noticed that if I clicked on days prior to Yesterday, there is a delay THE FIRST TIME I click on a specific day, as if it's retrieving data right then. That delay and presumed data retrieval doesn't repeat if I navigate away and then come back to that same historical day.
That makes me wonder if the logic that decides whether to retrieve data upon load of any given day is only checking if the app already has *any* data for the day, rather than a more robust check of whether the last data retrieval date in the app for that day's data is after the end of that display day.

**Comment by Greg15** [comment]
It's just after midnight local time, and I haven't check the weather charts for 8 hours. The issue definitely repeats itself. "Yesterday" only shows data through 4pm (which was when I last checked the charts, but that was when that data was part of the "Today" page but is now part of the "Yesterday" page because it's now just after midnight). A pull-down refreshes it correctly. I would think better automatic refresh criteria could be coded.
![Screenshot_20221013-001157.png](https://user-images.githubusercontent.com/70354350/195508096-74118437-f85f-4fe8-a396-aab2e3f9d5f3.png)

**Comment by PavlosTze** [comment]
@Greg15 Thank you for the detailed responses and explanations. Due to your help I identified that this is a caching issue. We are looking into it if there is a way to override it instead of having the need for a swipe down.

**Comment by PavlosTze** [comment]
Thanks once again @Greg15 ! Fixed on the latest beta release :)
