### ISSUE TITLE
Add access to Settings on the Historical Charts page

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#144]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Android Application

### **Is your feature request related to a problem? Please describe.**
I frequently find myself needing and wanting to change settings for weather data units when viewing Historical Weather Charts. This is especially true during testing, but I anticipate the need will still continue during production use.
Right now, that requires navigating back to a different screen, accessing settings from that screen, changing weather units, then navigating back to the History screen. It's then even one more click if the desired day of History to view isn't Today.
I also find myself from History Charts page needing to get the app version number for bug submissions, so that's another reason this enhancement would help, although that is of secondary concern.

### **Describe the solution you'd like**
Similar to how access to Settings was provided on the Station Details page via a "..." Menu access control, I request a similar menu access control be added to the History page. Clicking the menu access control would reveal a single "Settings" menu item. After changing weather units and clicking the back arrow, the app should return to the same day of historical data that was displayed before clicking the Settings menu item.

### **Describe alternatives you've considered**
Continuing with all the extra clicks when wanting to see a chart render with different units.

### **Additional context**
Here are screenshots of what the menu access control looks like on the Station Details page and where it would go on the Historical Charts page.
![Screenshot_20221018-121919.png](https://user-images.githubusercontent.com/70354350/196503074-b46ca152-48fa-428f-b72e-dbf3a1691980.png)
![Screenshot_20221018-122025.png](https://user-images.githubusercontent.com/70354350/196503102-15e4baed-c981-4d8d-9c39-459a39b820e8.png)

**Comment by PavlosTze** [comment]
@Greg15 We discussed it internally, we don't plan to implement it as we don't think there would be a production-wise usecase for this feature.

In case anything changes in the future, we plan to reconsider it.

Thank you :)
