### ISSUE TITLE
Miscalculated Total Rewards

### ISSUE THREAD

**Issue by Gdev82** [WeatherXM/issue-tracker#146]
## WeatherXM Related Element
- Android Application
- Web App

## **Describe the bug**
On the android App, the total rewards on the card are miscalculated.  When the station is deployed for less than 30 days the Total rewards value and Total rewards value should match. Even though the 30d rewards report correctly, the total rewards are not correct.

The behaviour is the same on the web app as well, so it seems like a server issue and not an application issue

### **How To Reproduce**
1. Open the Android App
2. Click on the weather station of interest
3. Scroll down to rewards section
4. Notice the difference in the rewards

### **Expected behavior**
When a station is deployed for less than 30 days, the values of Total and 30d rewards should match

### **Screenshots**
![Screenshot_20221019-084539_WeatherXM](https://user-images.githubusercontent.com/28630392/196731652-e9523c9f-7f46-44d5-ab81-3feec9ffd67d.jpg)

### **Additional context**
You can check the two weather stations that I own Cold Teal Cirrus, and Hidden Merlot Thermometer as an example

**Comment by chatper** [comment]
This is fixed now, thank you for your feedback.
