### ISSUE TITLE
Historical Charts data point pop up blocks graph 

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#147]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

When clicking on a data point in the historical charts, the pop up bubble with weather information sometimes blocks the graph making it difficult to see the graph or choose the next point you want to investigate. 

### **How To Reproduce**
1. Go to see historical charts
2. Click on any point in the graphs
3. See that pop up bubble blocks graph.

### **Expected behavior**

Pop up bubble is in a fixed position in an area of the graph where there are no data points.(possibly top right corner of each graph).

Have the corresponding data point on the graph turn a different colour to know which point you have selected.

### **Screenshots**

![Screenshot_20221028-135044~2.png](https://user-images.githubusercontent.com/100298772/198731554-5988ad9a-982c-4779-89e7-881ee18a8149.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Google Pixel 2
 - OS: Android 11
 - Android App Version 3.2.4-6af5d0a

**Comment by PavlosTze** [comment]
This has been fixed in the release we published today. Thank you :)
