### ISSUE TITLE
Days are off in the app on historical view.

### ISSUE THREAD

**Issue by oharkins** [WeatherXM/issue-tracker#150]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website
- Web App

## **Describe the bug**
The days are behind on the app and on the website for the historical view. Today shows nothing, yesterday, shows today and it keeps going.  

### **How To Reproduce**
1. Go to Device History,
2. Click on Dates at the top
4. See the error today has no data. 

### **Expected behavior**
I expect to see today's data under today and previous days matching data from that day. 

### **Screenshots**

![Screen Shot 2022-11-07 at 10 09 16 AM](https://user-images.githubusercontent.com/5509758/200372903-27076eea-8c73-4563-9859-dddb01f7b798.png)

This is today, see that it ends at 10 AM 
![Screen Shot 2022-11-07 at 10 09 49 AM](https://user-images.githubusercontent.com/5509758/200373389-be952761-e23f-45dc-822e-177dd0f212d6.png)

This data was actually for Saturday. 
![Screen Shot 2022-11-07 at 10 09 08 AM](https://user-images.githubusercontent.com/5509758/200373074-ad58c642-2e3c-4926-b7cf-5b8a3e0ce483.png)

### **If Applicable: Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. 3.0.0]
 - Web App Version [e.g. 3.0.0], you can find it on the in-app Settings

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Android App Version [e.g. 3.0.0], you can find it on the in-app Settings
 - iOS App Version [e.g. 3.0.0], you can find it on the in-app Settings
 - Web App Version [e.g. 3.0.0], you can find it on the in-app Settings

### **If Applicable: Hardware (please complete the following information):**
 - Firmware Version [e.g. 0.3.5], you can find it by swiping right on the M5's screen

**Comment by oharkins** [comment]
GMT -6 I don't have android it does not show up as an option to see history on Iphone.

**Comment by PavlosTze** [comment]
@oharkins We just released a new version of the web app containing this fix. Can you please confirm this is fixed?

**Comment by oharkins** [comment]
Looks good to me!
