### ISSUE TITLE
UV INDEX chart allows selection of future data points

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#153]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
For all historical charts except the UV Index, you cannot choose a data point beyond "now". If you try to select any point in today's chart beyond the current time, the chart will instead act like you selected the current time.
The UV index chart behaves differently. If you try to select a point to the far right of the UV index chart, it selects the time of 11pm, even if that is in the future, and it shows a pop-up for that time.
In addition, if the current time is for example 1pm, the UV INDEX chart will also let you pick the future data points of 2pm, 3pm, 4pm, ... 9pm, 10pm, 11pm.

### **How To Reproduce**
1. Anytime before 11pm localtime, go to the historical charts
2. On any data position in the future for UV INDEX
3. Notice that it displays in the pop-up an actual data UV INDEX value of 0 and the selected future time
4. Contrast that to the behavior of any other weather parameter, where you cannot select a future data point 

### **Expected behavior**
UV INDEX historical chart interaction should be similar to other charts: selecting a future value should be impossible.

### **Screenshots**
![Screenshot_20221111-095922.png](https://user-images.githubusercontent.com/70354350/201541838-c5b19c5c-6315-49d4-a10b-07cdd0c793db.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version 3.2.4-6af5d0a

### **Additional context**
N/A

**Comment by PavlosTze** [comment]
Fixed on the latest beta version. Thank you!
