### ISSUE TITLE
Selecting a point in the historical UV Index chart does not show the lines for X-value and Y-value

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#154]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
When clicking on a data point in the UV Index historical chart, the corresponding vertical and horizontal data point lines aren't drawn that are shown in all other historical data charts. This causes a little bit more looking to confirm if the displayed pop-up is for the data point the user intended to click on with their finger.

### **How To Reproduce**
1. Go to historical weather data charts
2. Click on a data point in any chart except UV INDEX, for example, the Pressure Chart
3. Notice that the graph displays a vertical line for the time of the selected data point,and notice the graph shows a horizontal line for the weather data value of the selected data point
4. Now click on a data point in the UV INDEX. Notice that similar lines are not drawn.

### **Expected behavior**
The data point lines would display, just like is done in all other historical data charts

### **Screenshots**
![Screenshot_20221111-130742.png](https://user-images.githubusercontent.com/70354350/201542535-91856d27-3c68-4576-96b3-02565f09f6d9.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: Android version 10 
 - Android App Version 3.2.4-6af5d0a

### **Additional context**
I recognize that the UV Index chart is a bar chart, and all the other charts are line charts, so I recognize that they underlying chart features might not be the same. But when clicking on a data point in the UV Index historical chart, it always takes me a bit longer to confirm if the displayed pop-up is for the data point I intended to click on with my finger. It's a little disorienting, and is a bit more frustrating than need be when trying to click on a particular data point and fat-fingering the wrong data point.

**Comment by RevNotDev** [comment]
Using Bluestacks I get the same happening as Greg.

**Comment by PavlosTze** [comment]
Thanks for that @Greg15 and @RevNotDev . Actually this is a different bug, the bars **should** get a different color when selected, whereas they didn't. I have implemented a fix that will be out in the next release, where the bar selected will get painted in a different color.

**Comment by PavlosTze** [comment]
> I assume that the bar color change won't indicate which data point is selected if selection is a UV INDEX of zero, since no bar?
> 
> My guess is that it's the best option available, but still not as complete as the data point selection feedback in line charts

Unfortunately this functionality isn't available in the charts' library, but even if it was I am not sure that would be a correct one as a bar isn't an actual data point like a line consists of many data points.

But in any case, we will think if there is another way to show it in a redesign we are doing regarding the historical charts and especially the popup/highlighting of values.

**Comment by PavlosTze** [comment]
Fixed on the latest beta version. Thank you!
