### ISSUE TITLE
Explorer Zooming Bug 

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#155]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
When zooming in on the New Zealand Christchurch station in the Explorer the view gets quickly moved (or 'thrown') to the left. This only seems to happen when New Zealand is not quite central.

### **How To Reproduce**
1. Go to https://explorer.weatherxm.com/
2. Find New Zealand
3. With New Zealand in the centre, scrolling in to the Christchurch station works fine
4. Move New Zealand slightly to the left and try and zoom in again. Slow or fast gives the same result of being 'thrown' to the left.

### **Expected behavior**
To not have the view move quickly to the left when zooming in on a station

### **If Applicable: Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome
 - Version: 107.0.5304.107 (Official Build) (64-bit)

https://user-images.githubusercontent.com/46647866/202021554-88881d03-1ac7-4d34-ba5f-fe22cf5ddca4.mp4

### **Additional context**
Couldn't reproduce the bug on the mobile version of Explorer (on iOS on Safari).
Have tried in a few other random places but have only seen this bug for the New Zealand station.

**Comment by PavlosTze** [comment]
Hey @RevNotDev , actually this is a Mapbox issue, first reported here: https://github.com/mapbox/mapbox-gl-js/pull/12238 . Good news is that they have actually fixed it and it's on the version 2.11 of the library we use: https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.11.0 which released 4 days ago. We are currently on 2.10, so we will upgrade it and on our next explorer release it will be fixed.

Thanks for reporting that! That was a good catch!

**Comment by RevNotDev** [comment]
At least it's already been fixed then, nice and easy resolution. Thanks for the update!

**Comment by PavlosTze** [comment]
Fixed on the latest explorer release :)
