### ISSUE TITLE
Historical UV chart is "active" on days when no weather data was recorded.

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#156]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

For days when the M5 was frozen/offline, Historical charts shows each chart as "No historical weather data could be found for this day" except for the UV chart, which shows the usual graph but with no data.

### **How To Reproduce**
1. Go to historical charts
2. Click on a day when the M5 was offline.
3. Scroll down to UV chart

### **Expected behavior**

All charts display the same message on days with no data.

### **Screenshots**

![Screenshot_20221119-195318.png](https://user-images.githubusercontent.com/100298772/202885937-4e196f36-7cc5-4c8f-8dd1-b72a71069b47.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**

 - Device: google pixel 2 
 - OS: android 11
 - Android App Version  3.2.4-6af5d0a

**Comment by PavlosTze** [comment]
Fixed on the latest beta version. Thank you!
