### ISSUE TITLE
Web Explorer Empty Hex

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#157]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Web App

## **Describe the bug**
There is an empty hex on web explorer when you refresh the webpage

### **How To Reproduce**
1. Go to 'explorer.weatherxm.com'
2. Click on a station and zoom
3. Wait a few minutes and refresh the page

### **Expected behavior**
Have a painted hex.

### **Screenshots**
![IMG_20221123_092958.jpg](https://user-images.githubusercontent.com/100304233/203492562-4572fa40-11db-4e83-86ed-7dedb2a93c81.jpg)

### **If Applicable: Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome 
 - Version 107.0.5304.107 64-bit
 - Web App Version 1.4.4

### **Additional context**
I've tried it twice. With quick refresh there is no problem.
After the bug is presented if you refresh it gets fixed

**Comment by PavlosTze** [comment]
Fixed on the latest explorer release :)
