### ISSUE TITLE
Missing wallet address warning flashes upon app opening

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#158]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

Every 5-7 times the Android app opens a "Wallet address is missing" warning flashes above the list of stations very briefly, even though there is a wallet address already associated with the account.

### **How To Reproduce**
1. Go to android app
2. Open app repeatedly until warning is observed.

### **Expected behavior**

Warning appears and stays if there is no wallet

No warning appears if there is a wallet.

### **Screenshots**

![Screenshot_20221123-210315.png](https://user-images.githubusercontent.com/100298772/203699274-dd224995-869b-437a-9ebe-334de10ee887.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device:  Google Pixel 2 
 - OS: Android 11
 - Android App Version 3.2.5-f3e2a81

### **Additional context**

Video sent to Pavlos via Discord DM

**Comment by PavlosTze** [comment]
Fixed in the latest beta release. Thank you @Skallagrimmm :)
