### ISSUE TITLE
Pressure history numbers always hpa

### ISSUE THREAD

**Issue by wpaulson** [WeatherXM/issue-tracker#159]
## WeatherXM Related Element
- iOS Application

## **Describe the bug**
The pressure historical chart always shows values in hpa, even when inHg legend is shown. Ie. the number shown on the left side scale is in the 980 range, rather than the 30 range. 

### **How To Reproduce**
1. Go to Settings
2. Click on Pressure
3. Select inHg
4. Go to Weather Stations -> station -> History
5. Values shown are eg. 978 inHg
6. (Also same page Precipitation is misspelled)

### **Expected behavior**
Expected values in 29-31 range. Eg. 29.13 inHg

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iPhone 12
 - OS: iOS 16.1
 - iOS App Version 1.1.0

**Comment by PavlosTze** [comment]
Thank you for reporting that @wpaulson . We are working on it.

**Comment by PavlosTze** [comment]
This just got fixed in the latest release. Thank you :)
