### ISSUE TITLE
IOS App Crashes 

### ISSUE THREAD

**Issue by msandrew44** [WeatherXM/issue-tracker#160]
## WeatherXM Related Element
- iOS Application

## **Describe the bug**
When clicking on device in app, app will ‘crash’ up until first reward has been received. Then app works normally.

**Comment by PavlosTze** [comment]
Thank you for reporting that @msandrew44 , we are looking into it.

**Comment by PavlosTze** [comment]
@msandrew44 Could you please describe a bit more what does "crash" up means? Did your application actually crashed?

**Comment by RevNotDev** [comment]
I've seen a few people mention this on Discord, but I'm not 100% sure if they mean freezes (and needs to be force closed) or closes by itself. One person said the app 'dies' when they tap on their station which I assume means closes.

**Comment by PavlosTze** [comment]
I see. @msandrew44 can you please confirm you are on the latest version? We made a new release a few days ago.

**Comment by msandrew44** [comment]
Yep, I can confirm it is latest version. Must not be only one as someone on discord was able to quickly note to wait for a token payment and then it should stop crashing. That is exactly what happened.

Michael S. Andrew
Sent from mobile device
________________________________

**Comment by PavlosTze** [comment]
Thanks a lot @msandrew44.
