### ISSUE TITLE
M5 is randomly restarting multiple times during the day.

### ISSUE THREAD

**Issue by aledantas2k12** [WeatherXM/issue-tracker#161]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Hardware

## **Describe the bug**
M5 randomly restart during the day, so I am never sending 24h worth of data.

### **How To Reproduce**
Just wait and it will restart by itself. I am also using a tool to ping the device to check when it goes down.

### **Expected behavior**
Stay online 24h / day 

### **Screenshots**
N/A

### **If Applicable: Desktop (please complete the following information):**
N/A
 
### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
N/A

### **If Applicable: Hardware (please complete the following information):**
 - Firmware Version 0.3.22

### **Additional context**
N/A

**Comment by NikosTsiligaridis** [comment]
Hello
Please contact me in discord (Nikos#5040) so we can debug this together.

**Comment by lucatz70** [comment]
I have 2 M5 Weather stations. Both are exhibiting an issue I think is related to PS not being powerful enough. They worked fine for a day or 2 then started rebooting. I figured it may be power related and changed one out with a 10w PS. This one has resolved, the other I have not yet upgraded to 10w from 5w. Battery indicator would be Great!

**Comment by aledantas2k12** [comment]
Replaced Today with a 15W power supply. It restarted 2x after that :(

**Comment by NikosTsiligaridis** [comment]
@lucatz70 @aledantas2k12 What are your discord usernames?
Please contact me on discord (discord handle Nikos#5040)
