### ISSUE TITLE
Explorer station details displaying off screen on mobile

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#162]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
On the explorer on mobile (iOS Safari and app) when tapping on a station it doesn't show all the details, it's partly chopped off the bottom of the screen.

### **How To Reproduce**
1. Go to the explorer either through the app or on a web browser on a mobile device
2. Tap on any station
3. Tap on it again to show the details 
4. See the details partly chopped off the bottom of the screen

### **Expected behavior**
The details screen to load full screen so no details are chopped off the bottom

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/205179185-c538ce78-92b1-4fcd-a454-cfb797deb55b.png)
![image](https://user-images.githubusercontent.com/46647866/205179206-663ac0ad-f02f-4ef7-bbef-a5a4bbd46c28.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.1.2
 - Safari Browser 
 - iOS App Version 1.1.0 **(P.S. it's not shown in the settings section of the app)**

**Comment by PavlosTze** [comment]
Hello @RevNotDev , just to confirm, it is not scrollable in order to view all the details, right?

**Comment by RevNotDev** [comment]
It is scrollable in the web browser, but seems like an unnecessary step to have to scroll to see it. Seems more intuitive if the details screen just opened full screen.
In the iOS app it's a lot more clunky. You can kind of scroll, but it bounces back and you can't really see everything. You can swipe the window up so it stays full screen, but this is hit and miss when it works.
