### ISSUE TITLE
Wind units reverting to m/s.

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#163]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

Wind units were set to km/h months ago in Android app. Last two days app has been periodically signing me out (2 times today) as well as wind units reverting to m/s without being changed by user. (User set to km/h twice today and it reverted back upon sign in).

Station Boiling Vanilla Spring, but changed for all stations in users account.

### **How To Reproduce**
1. Go to station homepage 
2. See that wind units have been changed to m/s without input from user.

### **Expected behavior**

Settings stay in place until user changes them.

### **Screenshots**
![Screenshot_20221201-205228~2.png](https://user-images.githubusercontent.com/100298772/205220591-d2484292-81e1-493a-8d76-85999a8ab338.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Google Pixel 2 
 - OS:  Android 11 

 - Android App Version 3.2.7-cbfeae8
 

### **Additional context**
Only noticed in last 2 days, has happened 2 times per day so far. I get logged out, then when logged back in, wind is in m/s.

**Comment by Skallagrimmm** [comment]
Have not been able to repeat this since it occurred two days in a row.

**Comment by Skallagrimmm** [comment]
This just occurred again. Went to open the Android app, it had logged me off. Signed in and the wind units had been changed to m/s. All other units remain the same as I had them before.

**Comment by PavlosTze** [comment]
This has been fixed in the latest beta release. :)
