### ISSUE TITLE
Humidity y-axis values duplicated in iOS app

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#167]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- iOS Application

## **Describe the bug**
In historical data, when humidity stays at the same level all day or for the majority of the day, the y-axis values become duplicated. 

### **How To Reproduce**
1. Go to historical data 
2. Look at humidity 

### **Expected behavior**
Y-axis values to display correctly with no duplicated values 

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/205432830-7b0750de-24d5-4f29-8aa4-d891c83d4395.jpeg)

![image](https://user-images.githubusercontent.com/46647866/205432834-afe3675b-12c8-4331-8b7d-062bc11ec578.jpeg)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.1.2
 - iOS App Version 1.1.0 **(P.S. it's not shown in the settings section of the app)**

**Comment by RevNotDev** [comment]
Just noticed temp and pressure having the same bug now.
![image](https://user-images.githubusercontent.com/46647866/211740135-422644e8-5b12-45a7-a1fc-6cea00268a54.jpeg)
![image](https://user-images.githubusercontent.com/46647866/211740149-f0ac0e7c-b48a-44eb-8630-e5ed16407dd0.jpeg)

**Comment by pantelisss** [comment]
We couldn't reproduce the issue after several updates on this screen in the last versions. Please reopen it if you face the problem again. Thanks for the report 🙏
