### ISSUE TITLE
30-day Rewards Reporting Higher than All-time Rewards

### ISSUE THREAD

**Issue by slyck50** [WeatherXM/issue-tracker#169]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application
- Web App

## **Describe the Bug**
When viewing the Rewards panel in both the Android app and at https://app.weatherxm.com/, sometimes the "All" reward value is improperly reported, and actually shows less than the "30-day" total.  It appears to be off by one day's rewards.

### **How To Reproduce**
The error does not appear to be entirely consistent, but simply opening the app and scrolling to the Rewards tile (for a specific station) shows that all the other values are current and correct (temperature, humidity, etc.).  Sometimes, refreshing the page or swiping down in the app to refresh the app will cause the values to correct themselves, but not always.

### **Expected Behavior**
For stations that are less than 30 days old, the 30-day total and the All-time total should be the same.

### **Screenshots**
Screenshot from the web app on desktop:
![Screenshot 2022-12-05 095943](https://user-images.githubusercontent.com/17143949/205723527-fa7fc273-6bd9-4524-b77e-f2ff369af2f2.png)

Screenshot from the app on Android:
![Screenshot_20221205-101544_WeatherXM](https://user-images.githubusercontent.com/17143949/205723870-982484fd-d95d-4091-bfbd-2119cfb8bef2.jpg)

### **Desktop:**
 - OS: Windows 10 64-bit
 - Browser: Brave
 - Version: 1.45.133; Chromium: 107.0.5304.141
 - Web App Version: 1.07

### **Smartphone:**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android 12
 - Android App Version: 3.2.7-cbfeae8

**Comment by slyck50** [comment]
Sorry, I should have made that clear in the original post.  The higher value is correct (30D).  My station is Convective Banana Orographic.  Thanks for the quick response!

**Comment by tmavroeid** [comment]
@slyck50 Hello, can you please confirm that the `30D` amount is in sync with the `Total` amount?

**Comment by slyck50** [comment]
I'll keep an eye on it, but as of now, yes, the amounts are in sync (both in the Android app and the web app).  Thank you!

**Comment by tmavroeid** [comment]
Thanks you @slyck50.

**Comment by slyck50** [comment]
@tmavroeid So, when I opened the Android app today, the issue seems to still occur. As soon as the app opened, all of the weather data refreshed properly, but the rewards totals were again off.  If I completely close out of the app and then restart it, the values are in sync once again.
![Screenshot_20221219-113446_WeatherXM](https://user-images.githubusercontent.com/17143949/208487432-7f83470d-12a9-46a2-9d9b-c38d4a469cc6.jpg)
