### ISSUE TITLE
Station showing (--) no data when powered over USB (c)

### ISSUE THREAD

**Issue by bugmeeting** [WeatherXM/issue-tracker#170]
Hi,

## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Hardware

## **Describe the bug and how to reproduce**
After setting M5 and station on the rooftop, using included RF antenna, everything was working fine until now. After talking with folks from Discord, I tested few things, including using another cable, changing power source. Tested phone charger and external power bank, powering on/off few times, but M5 is not working when connected with external power. When I take cable out from M5, everything comes back to normal.

**Screenshot**

This is screenshot when M5 is connected with USB-c power supply

![station_issue](https://user-images.githubusercontent.com/110265034/206392460-7a5f111a-b48a-4b5e-ae74-ab59cf84a987.jpg)

### **If Applicable: Hardware (please complete the following information):**
 - Firmware Version - last one

**Comment by NikosTsiligaridis** [comment]
Hello
So if I understand correctly, with mains power supply you get "--" on the screen (no weather station reception) but while on battery (no power supply connected) it works?

**Comment by bugmeeting** [comment]
**Update** 

@NikosTsiligaridis @PavlosTze 

I have temporary solution. As mentioned before, I decided to let M5 run on battery, once battery was discharged I plugged back regular power supply and station is working little bit over hour now without issue. Will follow up over day.

**Comment by bugmeeting** [comment]
**Update 1**

@NikosTsiligaridis @PavlosTze 

After battery was fully charged (I guess), same -- was seen on the screen, no data, on the app side I could see "offline" status again. I decided to change tactics, this time I didn't want to wait battery to discharge. I powered down M5 completely for about 5-10min, power on M5 connected directly using external power supply and it's working again, or I can say for now. Hope don't stop over night again. Firmware is 0.3.22. I didn't mentioned before I thought all station have the same version.

**Comment by NikosTsiligaridis** [comment]
@bugmeeting Please try the following
1. Disassemble the device using the provided tool and following this guide: https://docs.weatherxm.com/wifi-m5-bundle/m5-troubleshooting
2. Separate the stacks and put them back together in this order: White -> Gray -> Blue -> Black (Default is White -> Blue -> Gray - >Black)

See if that helps.

**Comment by rribeirom** [comment]
Hello all,
Just to keep it documented as @NikosTsiligaridis already knows this problem. All the information requested was sent by DM in Discord.
Since December, 7th my device is showing "--" in the screen. Already changed battery, changed charger and cable and changed order stacks.
Could someone give me an update of the problem?

![image](https://user-images.githubusercontent.com/63549772/212491324-552d3920-79d3-4bd5-b654-7c841a15b3aa.png)

![image](https://user-images.githubusercontent.com/63549772/212491349-c73cef9d-e863-4510-b94a-29a27010e59d.png)

![rn_image_picker_lib_temp_59ebc836-b55f-446d-862f-a7a2a9fdb994](https://user-images.githubusercontent.com/63549772/212491377-992d4862-9754-4319-b791-e824b3826942.jpg)

**Comment by gkoumanos** [comment]
Could you please report here if the issue is still present after the latest 0.10.1 OTA on Friday? Include your station name too please.

**Comment by rribeirom** [comment]
> Could you please report here if the issue is still present after the latest 0.10.1 OTA on Friday? Include your station name too please.

Hello,
The station was replaced and the old one was sent back.
