### ISSUE TITLE
Temperature dips below the X- Axis on the historical charts.

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#173]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

In today's historical chart, the temperature line has dipped below the x-axis. No amount of zooming in or out changes it.

### **How To Reproduce**
1. Go to Historical charts for station Joyous Cyan Mesocyclones
2. View Temp chart 

### **Expected behavior**
Not this

### **Screenshots**
![Screenshot_20230113-122111.png](https://user-images.githubusercontent.com/100298772/212413080-c269e809-aef3-4892-aa2d-5dcb40a4a8a1.png)

### **If Applicable: Desktop (please complete the following information):**
 
 - Version 3.2.8-b6ab80f
 

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Google Pixel 6a
 - OS: Android 13
  
 - Android App Version 3.2.8-b6ab80f

**Comment by PavlosTze** [comment]
Fixed in the latest beta release :)
