### ISSUE TITLE
Odd rain sensor readings 

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#176]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

- Hardware

## **Describe the bug**

The past week, the station Joyous Cyan Mesocyclones has recorded unusual precipitation readings in the historical charts. (All times in Pacific standard Time).

February 3rd @ 9pm - 11.9mm

February 4th @ 3pm - 11.9mm

February 5th @ 10am - 11.9mm

February 6th @ 4am - 12mm

February 7th @ 1am - 13.6mm
                        @ 5am - 13.4mm
                        @ 7am - 12.8mm
                        @ 10am - 25.3mm

February 8th @ 10am - 11.9mm

February 9th @ 1pm - 11.9mm

February 10th @ 6am - 12.5mm
                           @ 4pm - 11.9mm
         

My nearby station, Boiling Vanilla Spring is a few kms away and has not recorded anything close to those amounts of precipitation. I definitely see a pattern with the 11.9mm and they are often on days and times where there is no real precipitation outside.

I have checked the rain cup and confirmed there is nothing blocking it and it is mechanically functioning...

### **How To Reproduce**

Compare precipitation from February 3 to Feb 10th for Joyous Cyan Mesocyclones and Boiling Vanilla Spring 

### **Expected behavior**

I would expect similar precipitation readings.

**Comment by NikosTsiligaridis** [comment]
I enabled debug monitoring on your device, will keep you posted. Thanks for reporting.

**Comment by NikosTsiligaridis** [comment]
Looks like their measurements line up pretty well within tolerance (considering that they're a few kms apart):

Boiling vanilla spring / Joyous Cyan Mesocyclones
3th - 5th: 5.5mm / 5.5mm
6th - 8th: 20mm / 15mm
9th - 11th: 2mm / 2.5mm


![skallagrim](https://user-images.githubusercontent.com/34250462/218337123-a28d9a66-0a71-44bf-a77e-5d17f2248f42.png)

**Comment by Skallagrimmm** [comment]
@NikosTsiligaridis this is what I see from yesterday, first screencap is boiling Vanilla, second is Joyous Cyan...same.thing all week last week.

![Screenshot_20230212-131222.png](https://user-images.githubusercontent.com/100298772/218337421-1720edf1-3990-4030-ab18-0dbd13f295a9.png)

![Screenshot_20230212-131205.png](https://user-images.githubusercontent.com/100298772/218337425-afd4a233-42cc-441b-8535-92ce770ba8c9.png)

**Comment by Skallagrimmm** [comment]
Just an update...still seeing really high readings on the Joyous Cyan station the past week, and not on the Boiling Vanilla station. See screenshots (all from Joyous Cyan Mesocyclones historical charts.

![Screenshot_20230219-160057.png](https://user-images.githubusercontent.com/100298772/219983528-03bc80ba-789c-4a7e-a987-9c0a131750ca.png)

![Screenshot_20230219-160046.png](https://user-images.githubusercontent.com/100298772/219983525-56d4b9b1-3cb7-4f23-89ed-78a9648b242e.png)

![Screenshot_20230219-160120.png](https://user-images.githubusercontent.com/100298772/219983524-e9d8f509-1434-4d2d-a7d4-dc1d0b73737c.png)

![Screenshot_20230219-160111.png](https://user-im![Screenshot_20230219-160104.png](https://user-images.githubusercontent.com/100298772/219983527-55efa7ca-b646-4fc8-8c16-e35b7ee7693d.png)

23fa66-ec4b-4833-b232-7c968f5e0193.png)

![Uploading Screenshot_20230219-160104.png …]()

**Comment by Skallagrimmm** [comment]
Just an update...still seeing really high readings on the Joyous Cyan station the past week, and not on the Boiling Vanilla station. See screenshots (all from Joyous Cyan Mesocyclones historical charts.

![Screenshot_20230219-160057.png](https://user-images.githubusercontent.com/100298772/219983528-03bc80ba-789c-4a7e-a987-9c0a131750ca.png)

![Screenshot_20230219-160046.png](https://user-images.githubusercontent.com/100298772/219983525-56d4b9b1-3cb7-4f23-89ed-78a9648b242e.png)

![Screenshot_20230219-160120.png](https://user-images.githubusercontent.com/100298772/219983524-e9d8f509-1434-4d2d-a7d4-dc1d0b73737c.png)

![Screenshot_20230219-160111.png](https://user-im![Screenshot_20230219-160104.png](https://user-images.githubusercontent.com/100298772/219983527-55efa7ca-b646-4fc8-8c16-e35b7ee7693d.png)

23fa66-ec4b-4833-b232-7c968f5e0193.png)

![Uploading Screenshot_20230219-160104.png …]()

**Comment by Skallagrimmm** [comment]
Just an update...still seeing really high readings on the Joyous Cyan station the past week, and not on the Boiling Vanilla station. See screenshots (all from Joyous Cyan Mesocyclones historical charts.

![Screenshot_20230219-160057.png](https://user-images.githubusercontent.com/100298772/219983528-03bc80ba-789c-4a7e-a987-9c0a131750ca.png)

![Screenshot_20230219-160046.png](https://user-images.githubusercontent.com/100298772/219983525-56d4b9b1-3cb7-4f23-89ed-78a9648b242e.png)

![Screenshot_20230219-160120.png](https://user-images.githubusercontent.com/100298772/219983524-e9d8f509-1434-4d2d-a7d4-dc1d0b73737c.png)

![Screenshot_20230219-160111.png](https://user-im![Screenshot_20230219-160104.png](https://user-images.githubusercontent.com/100298772/219983527-55efa7ca-b646-4fc8-8c16-e35b7ee7693d.png)

23fa66-ec4b-4833-b232-7c968f5e0193.png)

![Uploading Screenshot_20230219-160104.png …]()

![Screenshot_20230219-160046.png](https://user-images.githubusercontent.com/100298772/219983667-bb3ee50e-5739-48ac-aa6d-cf79643ba39a.png)

**Comment by Skallagrimmm** [comment]
![Screenshot_20230219-160111.png](https://user-images.githubusercontent.com/100298772/219983687-f8427639-46d1-43c7-bf60-e5cb6de38798.png)

![Screenshot_20230219-160120.png](https://user-images.githubusercontent.com/100298772/219983686-fb668493-9b51-428d-9007-63887bcbc307.png)

![Screenshot_20230219-160104.png](https://user-images.githubusercontent.com/100298772/219983693-a15f3eb6-3d21-4973-84cd-69ca5a052650.png)

![Screenshot_20230219-160046.png](https://user-images.githubusercontent.com/100298772/219983692-1bf3c611-59af-41e0-a3fe-27d9be216ae0.png)

![Screenshot_20230219-160057.png](https://user-images.githubusercontent.com/100298772/219983694-bec671d6-d0ec-4b2a-80c7-99725a9f2696.png)

**Comment by NikosTsiligaridis** [comment]
The latest firmware versions of WS1000/M5 weather stations (`Boiling Vanilla Spring`) are using a different (better) rain rate calculation algorithm. The WS2000   (which `Joyous Cyan Mesocyclones` is) still uses the old algorithm since its still in beta stage. The new algo will be implement in a future firmware version.
