### ISSUE TITLE
Display last reported station firmware version in app for at least helium compatible models 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#177]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Android Application
- iOS Application

### **Is your feature request related to a problem? Please describe.**
A situation can occur when the owner or operator of a helium compatible weather station does not know if the station firmware is up to date or not, and trying to rely only on the in-app notice that a firmware update is needed doesn't help the process of elimination when something seems off overall with the situation. 
It will help immensely with troubleshooting if the app displayed the firmware version that the helium compatible weather station had last reported upgrading to, and also displayed the available/targeted version number.

I believe this information is already reported and stored on the network. It's likely also available for the M5 bundled units.

### **Describe the solution you'd like**
Add a "Device info" menu item to the station details page, that displays a popup or a new page that contains any relevant info about the hardware, firmware, etc. of the device.
This info at a minimum would contain last firmware version reported as being installed, and newest available/targeted firmware version.
The functionality is definitely needed at least for the helium compatible stations, but displaying the installed M5 firmware version, if available, would also help fleet owners check without having to travel to each station.

### **Describe alternatives you've considered**
Same functionality, but available from an icon on each station tile on the list of stations on the app homepage.

Different functionality - A feature in the app just for helium-compatible stations that can connect to the weather station via Bluetooth to real-time request the firmware version from the station.

Or, both the original design requested in this ticket (to obtain last reported firmware version) AND the in-app feature to connect to the helium-compatible station to identify the actual firmware version installed.(since it might theoretically be possible for those to be different).

### **Additional context**
The feature isn't just for an individual to check for themselves, but to get support from the team or community members in discord.
Several times, providing troubleshooting support in discord for the M5 bundled solution has involved having people check on the M5 screen what firmware version they have.
I know with helium hotspots, there were periodically needs to check if things were updated, which was done by using the app to connect to the device via Bluetooth.
Similar issues will happen with helium-compatible weather stations.

The only true way to know the current firmware version is to connect to the station, but I believe the last reported version would be more than sufficient, and would be way more viable for owners managing fleets of stations.

 Here is where I am proposing the new menu item is placed ![Screenshot_20230223-143736.png](https://user-images.githubusercontent.com/70354350/221029522-6b29d548-d7c8-4f1a-a8f8-d985f8ab8a8e.png)

**Comment by PavlosTze** [comment]
Hey @Greg15 , this is on our TODO list and one of our next features. We will add a detailed `Device Info` screen that will contain not only this but useful other metadata as well. Thank you :)

**Comment by PavlosTze** [comment]
This has been fixed in the release we published today on Android, the iOS is following up in the next days as well. Thank you :)
