### ISSUE TITLE
GPS Signal lost

### ISSUE THREAD

**Issue by Dean12692** [WeatherXM/issue-tracker#179]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Web App
- Hardware

## **Describe the bug**
I have not touched my M5 miner for months.  GPS signal has been lost, GPS antenna is plugged in and device restarted several time with change.  The lost GPS signal is causing the miner to not show up in a hex on the explorer.

**Comment by NikosTsiligaridis** [comment]
What is the name of your device?  (you can DM me in discord if you don't want to post it here)

**Comment by Dean12692** [comment]
Το βρήκα. My Neighbor grabbed it on accident.

**Comment by gulliverrr** [comment]
Glad you got it working. Please confirm and close this issue. Thanks!

**Comment by Dean12692** [comment]
Oh I'm sorry that was a response to another issue. But my miner is expert garnet snowstorm I have gotten GPS restored by walking outside

**Comment by Dean12692** [comment]
Actually it looks like I get signal only when being directly outside. Every time I go back in I loose the signal again.

**Comment by gkoumanos** [comment]
Could you please confirm that you use the external GPS antenna with the long cable connected to the grey stack and the connector for external antenna is properly in place. For the last past you would need some tools to open your M5.
Here are the steps (toggle the bottom section "M5 LoRa Antenna Installation Instructions"):
https://docs.weatherxm.com/wifi-m5-bundle/m5-troubleshooting
