### ISSUE TITLE
'7 Days Forecast' Spelling

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#18]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable:

- Android Application

### **Is your request related to a problem? Please describe.**
The spelling of '7 Days Forecast'

### **Describe the solution you'd like**
I believe the correct spelling should be '7 Day Forecast'

**Comment by PavlosTze** [comment]
Thanks @RevNotDev . Fixed internally. Will be out on a future version.
