### ISSUE TITLE
iOS No Data "Last Seen"

### ISSUE THREAD

**Issue by Rizzero** [WeatherXM/issue-tracker#181]
![1A20068F-FDB1-43D5-835C-9BD0041C6E2F](https://user-images.githubusercontent.com/126748809/222338652-a19d401f-4e6d-42ad-8b5c-a385e909648c.png)

> ## WeatherXM Related Element

Please pick one of the following WeatherXM elements that are applicable for this bug:

- iOS Application

## **Describe the bug**
When confirming the data for the weather station located in Alaska "Hot Umber Zenith" it shows that the station was last seen 2022 years ago. 

### **How To Reproduce**
1. Go to the explorer
2. Click on Hot Umber Zenith"
3. Scroll down to "Last Seen"

### **Expected behavior**
I expected to see the actual date in which the station went offline. 

### **Screenshots**
Screen shot added.

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iPhone 14 Pro
 - OS: 16.3.1
 - Browser WeatheXM app
 - iOS App Version 1.3.0

**Comment by pantelisss** [comment]
Hello @Rizzero! Thank you for the report. There is a new version live now (1.3.1) which resolves the issue.
