### ISSUE TITLE
Variation in recorded height

### ISSUE THREAD

**Issue by rmmills** [WeatherXM/issue-tracker#183]
The M5 display shows a large difference in the recorded height of the weather station. During one day the recorded height was between 65 and 120m. A connection to between 9 and 12 satellites was active during this time

This is a constant issue, and something I have noted since the installation of the weather station.

Without any alteration of the installation, or any intervention on my part, the height recorded varies a great deal.

**Comment by NikosTsiligaridis** [comment]
GPS altitude is not a very accurate measurement param (as opposed to lat/lon) and it gets even worse as visible satellites decrease. We are working on a different method of specifying altitude (user input) as this affects the relative pressure param.
