### ISSUE TITLE
Web explorer incorrectly shows some M5 wifi stations as helium stations 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#184]
## WeatherXM Related Element
- Website (explorer)

## **Describe the bug**
Some set of conditions cause the explorer to show some M5 wifi stations as helium stations. I haven't been able to fully generate the range of possible conditions to identify the exact combo that causes the error, but I suspect the issue is when a hex has both helium-compatible stations and M5 stations, and the helium-compatible stations are online, but the M5 stations are offline. I'm suspecting that the offline status is having the explorer not use any data retrieved by the API for that station.

### **How To Reproduce**
1. Go to new version of web explorer released today 
2. Navigate to a cell that has both helium and wifi stations.
3. If the wifi stations show correctly, take them offline.
4. wifi stations display using the helium-compatible icon

### **Expected behavior**
The model/type for a station is always known, whether it is currently online or offline, and should properly display in the explorer, even when offline.

### **Screenshots**
![Screenshot_20230308-101837.png](https://user-images.githubusercontent.com/70354350/223772382-ef84c2cc-8430-4458-bca7-b728e0fa1adc.png)

In the above screenshot, Best Coconut Altitude is an M5 bundled station, but displays as a helium-compatible model (and is listed in 2nd position, since online stations are listed first)

Here it is correctly displaying as a wifi model when online (in first position, since online stations are listed first, and then I think alphabetically)

![Screenshot_20230308-132823.png](https://user-images.githubusercontent.com/70354350/223824482-34d2427b-df21-4d64-b06c-b9d3af5ffc36.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto G7 power 
 - OS: android version 10
 - Browser chrome

### **Additional context**
The android in-app explorer works correctly, so this appears to be specific to the web explorer rather than a backend API issue.

**Comment by Skallagrimmm** [comment]
You beat me to it...in this situation, there is only a Wi-Fi station that has been offline for many months and it is incorrectly represented as a helium station

![Screenshot_20230308-081722.png](https://user-images.githubusercontent.com/100298772/223779332-c3befe8d-baa1-4807-a469-dabcdf51288b.png)

**Comment by Greg15** [comment]
Ah, nice. So you've confirmed it doesn't require a mix of models in a hex. Any offline wifi model is displayed incorrectly.

**Comment by PavlosTze** [comment]
@Greg15 @Skallagrimmm We have reproduced it internally and fixed it. Thank you for catching this bug :)

**Comment by PavlosTze** [comment]
Fixed in the latest Web App version we just released. Thank you! :)
