### ISSUE TITLE
Historical charts: precipitation and solar don't display isolated data points 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#188]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
When historical data exists for a single hour, but not for the preceding hour or the subsequent hour, the precipitation and solar charts don't display any data point in the graphical chart for that isolated data hour

### **How To Reproduce**
1. Find a station that provided data during an hour, but did not provide data in the preceding or following hour, so that any data for the that hour would be an isolated data point in historical charts
2. Navigate to historical charts
3. Notice that most of historical data charts show the isolated hour of data as a point (temp, wind, humidity, pressure)
4. Notice that no visible data point appears for that isolated hour for precipitation or solar charts, although the textual display of the data points displays at the top of the chart when the time sample is clicked in the chart 

### **Expected behavior**
All charts should display data in the chart for any isolated hours

### **Screenshots**
In these screenshots, 5pm is the isolated hour of data provided as an example 
![Screenshot_20230518-110113.png](https://github.com/WeatherXM/issue-tracker/assets/70354350/1757fd4a-2389-4fd7-8439-e9f8bc97e0bb)

![Screenshot_20230518-110213.png](https://github.com/WeatherXM/issue-tracker/assets/70354350/f3b40bdd-715f-4513-8d67-c2630eb7a061)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto G7 power 
 - OS: android version 10
 - Android App Version 3.5.0-8462025

### **Additional context**
N/A

**Comment by PavlosTze** [comment]
@Greg15 This is fixed in the latest production release. Thank you!
