### ISSUE TITLE
Miner doesn't reconnect to wifi after a router restart or ISP outage.

### ISSUE THREAD

**Issue by bperham** [WeatherXM/issue-tracker#189]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Hardware

## **Describe the bug**
My M5 miner doesn't automatically reconnect to wifi after a router reboot or ISP outage.

### **How To Reproduce**
1. Unplug and plug in router
2. M5 miner doesn't reconnect.

### **Expected behavior**
Reconnect to wifi.

### **If Applicable: Hardware (please complete the following information):**
 - Firmware Version 0.3.27

**Comment by liliumjsn** [comment]
What is your M5's icon status?
What is your home network installation? Do you have any repeaters or anything else than a simple WiFi router?

**Comment by bperham** [comment]
The icon is red when disconnected and green after reconnecting.

It's just the Spectrum Internet Wifi 6 wireless router.
https://d15yx0mnc9teae.cloudfront.net/sites/default/files/WiFi-6-Guide-1-7-21.pdf

**Comment by gkoumanos** [comment]
Could you try disconnecting all wires from M5, move about 1m from the router and then reset M5.
Report back the result. Please confirm your SSID does not have a space or other special character and it is a 2.4GHz (Not 5GHz). Please also report back the security/authentication type you have set in the router.
If above test didn't change anything, use another phone as hotspot with SSID: WXM and password: 12341234 and try WiFi Config again.

**Comment by bperham** [comment]
> 1. Please confirm your SSID does not have a space or other special character and it is a 2.4GHz (Not 5GHz).
Sorry I didn't know what the SSID was until I researched it. Turns out, yes, my network name did have a space in it. I've removed the space so hopefully that will fix the problem.

**Comment by gkoumanos** [comment]
Did you try restarting the router after the change to see if M5 reconnects automatically?

**Comment by bperham** [comment]
Yes, I restarted it this morning and it reconnected. So it has problems
automatically reconnecting if there is a space in the network name.

**Comment by gkoumanos** [comment]
It is generally good practice to not have spaces in SSID:
https://www.reddit.com/r/tmobileisp/comments/vt83db/why_cant_i_make_a_wifi_ssid_with_a_space_in_the/
Glad you fixed it and learned something new as well :)
