### ISSUE TITLE
Windows pass through cable for GPS module

### ISSUE THREAD

**Issue by DrCryptoN3rd** [WeatherXM/issue-tracker#19]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Weather Station

### **Is your feature request related to a problem? Please describe.**
If I place the GPS module behind my double glassed window I don't get any satellites. 

### **Describe the solution you'd like**
What would be great is to have a flat "windows-pass-through-cable" like they exist for other cables (like LAN or TV) see pictures.

### **Describe alternatives you've considered**
Another option would be to install the GPS module into the weather-station itself.

### **Additional context**
![71408_2](https://user-images.githubusercontent.com/84883231/155934648-ea3a06ce-ab09-4599-bd39-82d8c75660ec.jpeg)
![image](https://user-images.githubusercontent.com/84883231/155934675-4c532d27-9689-4066-aaa5-493c565d9090.jpeg)

**Comment by oharkins** [comment]
Most modern windows are rf blocking one would do better to put it right next to the wall as wood blocks less rf than glass with any sort of UV blockers.
