### ISSUE TITLE
Precipitation values are not shown

### ISSUE THREAD

**Issue by fabgio** [WeatherXM/issue-tracker#191]
## WeatherXM Related Element:
- Rest response json
- Hardware

Rest call 

GET https://api.weatherxm.com/api/v1/cells/871ea0976ffffff/devices
Accept: application/json

the response body  is: 

[
  {
    "id": "cb5881e0-b99e-11ed-95eb-b351f0b0cc44",
    "cellIndex": "871ea0976ffffff",
    "name": "High Watermelon Sandstorm",
    "profile": "Helium",
    "timezone": "Europe/Rome",
    "isActive": true,
    "lastWeatherStationActivity": "2023-07-23T09:52:49+02:00",
    "current_weather": {
      "timestamp": "2023-07-23T09:52:49+02:00",
      "temperature": 27.6,
      "humidity": 53,
      "wind_speed": 1.2,
      "wind_gust": 2.7,
      "wind_direction": 184,
      "solar_irradiance": 445.2704918032787,
      "uv_index": 3,
      "precipitation": 0,
      "pressure": 1014.5,
      "icon": "partly-cloudy-day",
      "precipitation_accumulated": 0,
      "dew_point": 17.162718505619466,
      "feels_like": 28.46359824512001
    }
  }
]

The precipitation and precipitation accumulated values are stuck   to  0 even if it is raining or  rained shortly ago.
Any tip?

**Comment by giannisdravilas** [comment]
Hello, it indeed seems that the precipitation values recorded by your station are very small or zero. Could you please check that the rain gauge is not blocked (e.g. by dirt or leaves) and also provide us with a photo or video of the surrounding area near the station?

**Comment by fabgio** [comment]
Ok following your suggestions the issue was solved, everything works fine now 
Thanks!
