### ISSUE TITLE
Large solar reading discrepancy with local cell

### ISSUE THREAD

**Issue by Focusarmy** [WeatherXM/issue-tracker#192]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Hardware

## **Describe the bug**

Large solar reading discrepancy with local cell v's my beta version.
### **How To Reproduce**

Cells are:

Exotic Pewter Flurry
Tricky Platinum Summer (beta)

### **Expected behavior**

Similar solar reading

### **Screenshots**

Attached.  Two different days 

![Screenshot_20230813-140949](https://github.com/WeatherXM/issue-tracker/assets/101021392/adff033d-34c9-4c3e-b22a-1cc2a7ecff92)

![Screenshot_20230813-140959](https://github.com/WeatherXM/issue-tracker/assets/101021392/fe0e5866-2a66-4e71-8078-1325806f4649)

![Screenshot_20230812-144250](https://github.com/WeatherXM/issue-tracker/assets/101021392/0d605e21-8470-400a-a24b-c3036ec24c97)

![Screenshot_20230812-144236](https://github.com/WeatherXM/issue-tracker/assets/101021392/0a408642-b97c-48c0-9363-bc20fcc15063)

### **If Applicable: Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. 3.0.0]
 - Web App Version [e.g. 3.0.0], you can find it on the in-app Settings

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Android App Version [e.g. 3.0.0], you can find it on the in-app Settings
 - iOS App Version [e.g. 3.0.0], you can find it on the in-app Settings
 - Web App Version [e.g. 3.0.0], you can find it on the in-app Settings

### **If Applicable: Hardware (please complete the following information):**
 - Firmware Version [e.g. 0.3.5], you can find it by swiping right on the M5's screen

### **Additional context**
Ongoing.  My device is pointing North and has no obstructions.

**Comment by Focusarmy** [comment]
Are devices not meant to point north?

**Comment by steeve88** [comment]
Hello,

as I can see your station is a WG-1000 model (M5/WiFi). Please confirm this info. If this is the case, there is a symbol on the outdoor sensor indicating where the 'WEST'. You should orientate your outdoor sensor according to that. Please always use the geographical and the magnetic north. 

Practically, the rain gauge should point to the north. Please have a look at our video, where we thoroughly explain everything about the installation
https://www.youtube.com/watch?v=J-dSXNLX4nk

If you need further assistance, we are at your disposal.

**Comment by Focusarmy** [comment]
Good to know.  Wasnt my station though.  I did say that in my post!

**Comment by PavlosTze** [comment]
The issue will probably be fixed when the user updates the firmware, but as I checked it's still on 0.3.12, we can check it by following the station and viewing the "Station Settings".

I'm closing this issue and we will keep an eye on it if it's still happening after the firmware update.
