### ISSUE TITLE
Settings options: Wind speed

### ISSUE THREAD

**Issue by DrCryptoN3rd** [WeatherXM/issue-tracker#20]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Weather Station

### **Is your feature request related to a problem? Please describe.**
The settings don't allow to change display of wind speed in different units.

### **Describe the solution you'd like**
Add other units to windspeed (like km/h, knots, beaufort etc.)

### **Describe alternatives you've considered**
leave at is to force everyone to think in m/s

### **Additional context**
From Wikipedia:
[Meters per second](https://en.wikipedia.org/wiki/Meters_per_second) (m/s) is the [SI unit](https://en.wikipedia.org/wiki/SI_unit) for velocity and the unit recommended by the [World Meteorological Organization](https://en.wikipedia.org/wiki/World_Meteorological_Organization) for reporting wind speeds, and is amongst others used in weather forecasts in the [Nordic countries](https://en.wikipedia.org/wiki/Nordic_countries).[[2]](https://en.wikipedia.org/wiki/Wind_speed#cite_note-2) Since 2010 the [International Civil Aviation Organization](https://en.wikipedia.org/wiki/International_Civil_Aviation_Organization) (ICAO) also recommends meters per second for reporting wind speed when approaching [runways](https://en.wikipedia.org/wiki/Runway), replacing their former recommendation of using [kilometers per hour](https://en.wikipedia.org/wiki/Kilometers_per_hour) (km/h).[[3]](https://en.wikipedia.org/wiki/Wind_speed#cite_note-3) For historical reasons, other units such as [miles per hour](https://en.wikipedia.org/wiki/Miles_per_hour) (mph), [knots](https://en.wikipedia.org/wiki/Knot_(unit)) (kn)[[4]](https://en.wikipedia.org/wiki/Wind_speed#cite_note-4) or [feet per second](https://en.wikipedia.org/wiki/Feet_per_second) (ft/s) are also sometimes used to measure wind speeds. Historically, wind speeds have also been classified using the [Beaufort scale](https://en.wikipedia.org/wiki/Beaufort_scale), which is based on visual observations of specifically defined wind effects at sea or on land.

**Comment by EmperorDRT1** [comment]
I'm not having any issues with changing the wind speed. Can you send a picture and include your app version?

![SmartSelect_20220228-003838_WeatherXM](https://user-images.githubusercontent.com/44149620/155936165-aeb925e0-0c5c-4990-a517-c36aebb5af02.jpg)
Android App Version 3.0.3-3f653e9

**Comment by DrCryptoN3rd** [comment]
I mean on the device itself:
![IMG_1098](https://user-images.githubusercontent.com/84883231/155941430-ec18a517-477d-407f-83c1-000b3bce90ba.jpeg)

**Comment by NikosTsiligaridis** [comment]
This will be rolled out in the next update very soon.
