### ISSUE TITLE
Temperature display bug on explorer on iOS

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#22]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
When viewing the Explorer on iOS web browser, when the temperature has 3 digits it pushes the 'C' after '°' onto the next line. 

### **How To Reproduce**
1. Go to https://explorer.WeatherXM.com on iPhone
2. Click on any station showing 3 digits for temperature
4. See display bug for the 'C'

### **Expected behavior**
The whole temperature including units to show on one line

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/156018472-0cd48641-687d-4b92-b666-7a73f74679f4.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.3.1
 - Browser: Stock - Safari

**Comment by PavlosTze** [comment]
@RevNotDev Can you please check again if this is fixed or not?

**Comment by RevNotDev** [comment]
> @RevNotDev Can you please check again if this is fixed or not?

Looks fixed to me 👍🏻

**Comment by PavlosTze** [comment]
Great! Then the fix we applied is working. Thank you! I'm closing this issue :)
