### ISSUE TITLE
[BUG on selecting future forecast]

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#24]
## WeatherXM Related Element

- Android Application

## **Describe the bug**
It's possible to have two hours selected in the app when seeing a future forecast and now forecast

### **How To Reproduce**
1. Go to Device
2. Click on an hour other than now
3. Swipe down to refresh the page
4. After finishing the refresh click on another hour. Now both are selected.

### **Expected behavior**
Only one being selected per time

### **Screenshots**
![Screenshot_2022-03-02-21-11-19-431_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/156432638-20459ace-61bf-459d-9d29-e8d7e0887868.jpg)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Android App Version [3.0.3-3f653e9], you can find it on the in-app Settings

**Comment by PavlosTze** [comment]
Good catch @kkatsoulak . We fixed it internally. It will be fixed in the next beta version. Thank you.
