### ISSUE TITLE
[Temperature reads as -0⁰ in some locations]

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#25]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

Android Application

## **Describe the bug**

In 7 day forecast one of the 0⁰ temperatures displayed as -0⁰. I think this issue was fixed in other locations but just saw it again, see screenshot.

### **How To Reproduce**

1. Go to 7day forecast (Boiling Vanilla Spring)

### **Expected behavior**

No negative beside 0⁰

### **Screenshots**

![Screenshot_20220304-105021.png](https://user-images.githubusercontent.com/100298772/156824670-d96974c0-29ba-4e66-8e53-b792c327f1b4.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: [Google  Pixel 2
 - OS: Android 11
 - Android App Version 3.0.4-dace911

### **If Applicable: M5 (please complete the following information):**
 - Firmware Version [e.g. 0.3.5], you can find it by swiping right on the M5's screen

**Comment by PavlosTze** [comment]
Thank you @Skallagrimmm . Will fix it.

**Comment by PavlosTze** [comment]
Fixed @Skallagrimmm . I'm closing this, the fix will be available on the next beta release. :)
