### ISSUE TITLE
Offline Miner Messages

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#26]
## WeatherXM Related Element

- Android Application

## **Describe the bug**
There is a mixed message when the miner is offline in the app. It says that the station is offline but at the same time "Last seen now"
Look at the attached photos. Also inside the weather readings when offline there is a "null last seen now"

### **How To Reproduce**
1. Turn off miner
2. Open the app

### **Expected behavior**
If it's offline then display the hours the miner was last online

### **Screenshots**
![Screenshot_2022-03-09-11-31-39-047_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/157505797-726582b3-3762-490a-8968-0ba0557d7e46.jpg)
![Screenshot_2022-03-09-11-43-03-314_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/157505815-c0e81456-080d-4c0b-bdd8-00f23a5161bb.jpg)
### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Android App Version [3.0.4-dace911], you can find it on the in-app Settings

**Comment by PavlosTze** [comment]
Thank you @kkatsoulak ! We are investigating it.

**Comment by kkatsoulak** [comment]
An update on the bug. It now shows null even when online
![Screenshot_2022-03-11-07-31-20-723_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/157808643-78d96940-50ff-4d4e-ac55-d37a7209a35f.jpg)
