### ISSUE TITLE
[SUGGESTION] Ability to sleep/dim M5 miner screen

### ISSUE THREAD

**Issue by joshuajaharwood** [WeatherXM/issue-tracker#27]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- M5 Firmware

### **Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

The M5 screen can be quite bright/distracting if it's in the same room you sleep in.

### **Describe the solution you'd like**

Having the ability to dim/turn the screen off (similarly to locking a phone) would fix this.

### **Describe alternatives you've considered**

You could also have the screen dim/turn off during the night time, I suppose?

### **Additional context**

N/A

**Comment by PavlosTze** [comment]
Thank you @joshuajaharwood . That's something we will implement for sure in a future version :)

**Comment by NikosTsiligaridis** [comment]
Hi @joshuajaharwood, this is already implemented and will be rolled out along with other features in the next OTA update soon :)
