### ISSUE TITLE
Sharing of weather data - connected accounts

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#3]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Weather Station

### **Is your feature request related to a problem? Please describe.**

Share my weather station data to people on my network ex my wife, kids, work partner without sharing my account details ( email, password etc)

### **Describe the solution you'd like**
A trusted shared account by email and authentication. Maybe limit it to a number of free accounts and then charge for more.

### **Additional context**
Those connected accounts won't have the ability to share data to others

**Comment by PavlosTze** [comment]
Thank you for your suggestion. At this point of time this is not in our priorities. But we will reconsider it in the future.

**Comment by PavlosTze** [comment]
Hello, this has been implemented in the latest release in mobile clients by the "follow/favorite" feature. Thank you!
