### ISSUE TITLE
[BUG] Weather icon for current time never changes

### ISSUE THREAD

**Issue by jarodspence** [WeatherXM/issue-tracker#30]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
The Icon representing the current weather status is always the same (fog?).

### **How To Reproduce**
1. Open the App
2. Click on a weather station
3. The Icon is displayed in the big blue tile and also beneath in the small tile representing the current time

### **Expected behavior**
The Icon should represent the current weather sun/rain/...

### **Screenshots**
![Screenshot_20220321-184402_WeatherXM](https://user-images.githubusercontent.com/29737923/159333244-0ceb5991-6482-4bca-997a-af3eb08bc9f9.jpg)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Samsung Galaxy Tab A
 - OS: Android 10
 - Android App Version 3.0.5-0fecb19

**Comment by PavlosTze** [comment]
This is a known bug. We are working into it :)
