### ISSUE TITLE
Change wording for M5 backlight settings

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#31]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- M5 Firmware

### **Is your feature request related to a problem? Please describe.**
The current backlight setting wording is confusing as the % selected is the opposite of what is happening on the screen.

### **Describe the solution you'd like**
Change 'Backlight fade' to either 'Idle Backlight' or 'Idle Brightness' 

### **Describe alternatives you've considered**
Keeping the wording 'Backlight fade' but the % values would need to be opposite to what they are now. For example, 25% backlight fade would be brighter than 75% backlight fade.

**Comment by OneCDNGuy** [comment]
Alternative suggestion, how about naming it 'Idle Brightness'

**Comment by NikosTsiligaridis** [comment]
After discussion with the beta group it was changed to a more descriptive "idle brightness".
