### ISSUE TITLE
Connection status & Battery indicator

### ISSUE THREAD

**Issue by snam11** [WeatherXM/issue-tracker#32]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Android Application
- Web Dashboard
- M5 Firmware
- Weather Station

### **Is your feature request related to a problem? Please describe.**
to install the station in the perfect spot, you need to consider the signal strength from station to the miner.
since not all the installation are easy (i.e. putting it on a roof of a multi apartment building), a way to monitor the connection status from the miner is a must have.
Plus if the station is placed in a spot not so easy to reach, monitoring the battery status on the miner is good too

### **Describe the solution you'd like**
after the connection between miner/station, a submenu or an icon showing the signal strength connection would be good.
Same submenu could be used to do a manual battery check test on the station to know when the battery need to be replaced (even once a year could be a pia if the station installation spot is not easy to reach)

**Comment by NikosTsiligaridis** [comment]
A signal indicator for the weather station and GPS is in the works.
There is no battery level information transmitted by the weather station that could be visualized for the user. However there is a "low  battery" warning signal that is sent by the weather station when batteries are under a preset threshold but I haven't tested this as to how reliable this information in. I will look into it and will implement it in one of the next updates.

**Comment by snam11** [comment]
k, thanx for the reply. Looking forward to test the signal indicator update!
