### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Placebo1** [WeatherXM/issue-tracker#33]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

Issue with app not showing the historical data even though everything is connected and looks fine with M5 device. Also app is reporting incorrect time. 

### **Screenshots**

![image](https://user-images.githubusercontent.com/100307673/161850748-401e5e8d-492b-46a0-ba8c-c4654d758f54.jpeg)

 - Android App Version [e.g. 3.0.5], you can find it on the in-app Settings

**Comment by PavlosTze** [comment]
@Placebo1 We have fixed it. Thank you for your report.
