### ISSUE TITLE
[SUGGESTION] - "Feels Like" temp included in  future forecasts

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#35]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:

- Android Application

### **Is your feature request related to a problem? Please describe.**

Suggestion, no problem.

### **Describe the solution you'd like**

Have the "Feels Like" temperature be included in future hourly, tomorrow and if feasible, 7 day forecasts.

**Comment by PavlosTze** [comment]
I have already passed this internally we will get back to this if it has any meaning or not.

**Comment by PavlosTze** [comment]
We have implemented it and will be there on the new API release.
