### ISSUE TITLE
Followed/Favorite Stations ability 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#37]
### WeatherXM Related Element

- Android Application

### **Is your feature request related to a problem? Please describe.**
When wanting to periodically check the weather at a station in an area of interest, each time we want to check, we currently need to use the explorer and scroll to the desired geographic area, click on the correct hex, drill down, and click on the desired station before being able to check the weather at that station.

### **Describe the solution you'd like**
It would be nice to be able to mark a station as a "Favorite" station or a "Followed Station" if wanting to periodically check it, and have favorite/followed stations easily accessible from the app.
Perhaps a "Favorite/Unfavorite" toggle, or a "Follow/Unfollow" toggle on each weather station's page within the in-app explorer (e.g., a Toggle-able Star on the upper right corner of the station . The toggle should not appear if the station is a station that you own.
Then, the home page of the app can have 2 tabs at the top. The default tab could be "My Stations", and a 2nd tab could be "Followed Stations" or "Favorite Stations". Followed Stations should not display token information to the user.

### **Describe alternatives you've considered**
Instead of tabs on the home page, the top section has owned stations (as today). If the user is following any stations, a section can appear below the owned stations, with a section header labeled "Followed Stations", populated with the list of followed stations.

### **Additional context**
![Screenshot_20220409-132553.png](https://user-images.githubusercontent.com/70354350/162587303-483d3f7e-ff59-478e-b738-b248a1a7c583.png)

**Comment by PavlosTze** [comment]
@Greg15 Thank you for your suggestion. This is an interesting feature but not in our current priorities at the moment. We will plan it accordingly and work on it in the future.

**Comment by PavlosTze** [comment]
Implemented in the latest release in our mobile clients! :)
