### ISSUE TITLE
'Feels Like' temp regularly showing higher than actual temp

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#38]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
The new 'feels like' temp is regularly showing higher temp than the actual temp.

### **How To Reproduce**
Compare the feels like temp to actual temp.

### **Expected behavior**
I would expect the feels like temp to be showing lower than the actual temp the majority of the time due to wind chill (UK based station)

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/162608920-9eb6db0d-9339-46fb-9b13-177c98b6a821.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
Device: Fire Tablet 7 (9th gen)
OS: Fire OS 7.3.2.2
Android App Version: 3.0.6-805d729

**Comment by Skallagrimmm** [comment]
I am also seeing this, Quite a difference at this moment in time...![Screenshot_20220410-005446~2.png](https://user-images.githubusercontent.com/100298772/162609484-867c9f29-4150-498e-bbee-22bc9289da72.png)

**Comment by Greg15** [comment]
Pavlos shared the wind chill formula in discord.
A Google search leads me to think that the formula shared is "correct", but only for valid values. The formula seemed to properly only attempt wind-chill calculation if air temperature was <=10°C, but it did NOT seem to also only attempt a wind-chill calculation for winds of 4.8km/hr or above.
Without that additional restriction, the wind chill calculation can erroneously produce a higher value than the air temperature.

**Comment by PavlosTze** [comment]
We are looking into it. A fix is coming soon.
