### ISSUE TITLE
[BUG] Terms for adding Wallet to app not available to read 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#39]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
When connecting a wallet to the weatherXM app, we are asked to acknowledge that we have read and accept the terms. However, there are no terms available anywhere to read.

### **How To Reproduce**
1. Within the app, click 'Connect Wallet'
2. Prepare to check the 'I have read and accept the terms' checkbox.
3. Observe the absence of any terms, any link to terms, any instructions for where to find the terms, and possibly any actual terms anywhere in the app or on the website, etc.

### **Expected behavior**
Either the terms available on the screen, or a link on the terms available on the screen

### **Screenshots**
![Screenshot_20220410-125957.png](https://user-images.githubusercontent.com/70354350/162633815-939f8473-fd0e-4bcd-b19c-2400a17e94bb.png)

### **Smartphone**
 - Device: moto g(7) power
 - OS: Android 10
 - Android App Version: 3.0.6-805d729

### **Additional context**
I recognize that we are only receiving testnet tokens at this time, so terms may be meaningless at this point. However, I believe the same address will work at mainnet on Polygon Mainnet, so many users might not revisit the "Connect Wallet" functionality at mainnet unless the app forces them to, so it's possible that a chunk of early users will have never agreed to any terms if there aren't terms implemented now. Implementing terms now might only require forcing <200 users to re-visit and accept terms.

**Comment by PavlosTze** [comment]
Thanks for reporting that @Greg15 . This just got fixed in the latest beta release therefore I am closing this issue.
