### ISSUE TITLE
[Formatting - ° in history data misplaced]

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#4]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
Formatting of data in history when placing markers

### **How To Reproduce**
1. Go to 'history data'
2. Click on 'charts'
4. See error on wind speed where  ° is misplaced

### **Screenshots**
![Screenshot_2022-02-23-17-04-08-595_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/155385380-e5446b12-a4b4-4f38-95ee-322bdd483c79.jpg)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**

 - Android App Version 3.0.2-21c4a34

**Comment by PavlosTze** [comment]
@kkatsoulak Thank you. This is fixed. Will be there on the next beta version. I'm closing this issue :)
