### ISSUE TITLE
[BUG] Inconsistent date formatting for locales where month normally comes first

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#40]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
Dates are displayed in 3 places in the app.  For those that are used to month coming first, it is a bit disorienting that in 1 place the month comes first, but in the other places, the number for the month comes 2nd.

### **How To Reproduce**
1. Become a user in a country that uses the Month before Day format, immerse yourself in the culture until the custom is embedded in how you interpret dates. While still in that country, and with your phone configured to use the customs of that locale...
2. Go to the home page in the app.
3. Click on a weather station.
4a. Scroll down and click on 'See Detailed WXM Rewards'. Notice month comes before day. 
4b. From step 3, click on 'Next 7 Days'. Notice that dates use dd/mm format common in much of the rest of the world instead of mm/DD format you are used to. Spend a moment to process it as your brain adjusts to the dates not making initial sense.
4c. From step 3, click on 'See Historical Charts'. Notice that dates use dd/mm format common in much of the rest of the world instead of mm/DD format you are used to. Spend a moment to process it as your brain adjusts to the dates not making initial sense.

### **Expected behavior**
In the 2 locations where date is displayed with numbers, use mm/dd format when the locale custom is mm/dd. That will be consistent with the locale, and will be comparable to the 3rd location that date is displayed.

### **Screenshots**
![Screenshot_20220410-132552.png](https://user-images.githubusercontent.com/70354350/162635067-844dfc82-ef61-453d-88d5-3bd701b8ea0f.png)
![Screenshot_20220410-132507.png](https://user-images.githubusercontent.com/70354350/162635072-5aa86854-4e32-4135-bddf-de0ea84298e5.png)
![Screenshot_20220410-132346.png](https://user-images.githubusercontent.com/70354350/162635077-329d905e-86d2-49fe-ab4d-57c0d3353e52.png)

### **Smartphone (please complete the following information that are needed for this bug):**
 - Device: moto g(7) power
 - OS: Android 10
 - Android App Version 3.0.6-805d729

**Comment by RevNotDev** [comment]
All looks good to me, no confusion here ;-)

**Comment by PavlosTze** [comment]
I have completed it internally and will be out on the next beta release.

**Comment by PavlosTze** [comment]
Should be fixed in the latest Android Beta version.
