### ISSUE TITLE
[BUG] Less than 2 y-axis labels still happens in some situations 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#41]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
In some situations, the y-axis still only has a single label. This makes it hard to interpret the data in that graph.

### **How To Reproduce**
1. Possibly wait for a trivial but non-zero amount of precipitation. Or, possibly let lose your helpful pet bird to perch on the rain funnel and make enough commotion to make the rain cup pivot.
2. In the app, navigate to and click 'See Historical Charts' for the weather station.
3. Notice that the trivial amount of rain registers visually as non-zero on the line chart, but is listed on the popup as 0.00 in of precipitation, and only a single y-axis label, for 0.00 in, exists. Notice that without clicking on the data to get a pop-up, you would think a non-trivial amount of rain would have fallen, due to the shape of the rainfall line on the chart.

### **Expected behavior**
A 2nd y-axis label should exist. I suspect that in the example shown, the 2nd y-axis point should be 0.01 in, even if the line then looks flat.

### **Screenshots**
![Screenshot_20220407-110522.png](https://user-images.githubusercontent.com/70354350/162636563-6cef6fc3-7a67-4f46-a859-e129c50c9dc2.png)
![Screenshot_20220407-110633.png](https://user-images.githubusercontent.com/70354350/162636574-0c1e2776-b99f-4d02-88cc-5832d992a658.png)

### **Smartphone**
 - Device: moto g(7) power
 - OS: Android version 10
 - Android App Version: not sure if I captured this with current version of 3.0.6-805d729, or with previous version.

**Comment by Greg15** [comment]
Awesome :)

**Comment by Greg15** [comment]
Pavlos, I found a related situation where I have NO y-axis labels for precipitation. Actual values are 0.00 in (when rounded).
Do you think your fix will address this one too, or should I open a separate issue?

![Screenshot_20220412-105342.png](https://user-images.githubusercontent.com/70354350/163004439-61ce8eff-329e-43c9-834b-0ac2d85fe4d2.png)

**Comment by PavlosTze** [comment]
@Greg15 I think my fix might work for this also, but I will have a look at it again. Not needed for a new issue, I'll check it :)

**Comment by Greg15** [comment]
The highest and lowest values all display as 0.00 inches on the value pop-up, so I suspect the actual values are between 0.001 and 0.009 inches inclusive (or 0.001 and 0.005 if rounding is used).

So I think the best I can offer is to suggest you pull the actual stored data associated with this station during the time period in question.

The station name is in the original pic (Furry Golden Downpour), and the time period is shown in the prior pic, and the additional ones below showing the value pop-ups for high and low values.

The times shown in the graph are UTC-5.

![Screenshot_20220412-110551.png](https://user-images.githubusercontent.com/70354350/163006837-87e70187-8688-40d3-a64a-a2ae5c968924.png)

![Screenshot_20220412-110613.png](https://user-images.githubusercontent.com/70354350/163006851-d1d9154b-21d2-46ab-a9c2-c8ad393c2676.png)

**Comment by PavlosTze** [comment]
I'm looking into it. Thank you Greg!

**Comment by PavlosTze** [comment]
Should be fixed in the latest Android Beta version.
