### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pienio1981** [WeatherXM/issue-tracker#42]
## WeatherXM Related Element

M5 Firmware or Weather Station

## **Describe the bug**
The pressure shown in the app is much too low - see below

![Screenshot_20220410-224618_WeatherXM](https://user-images.githubusercontent.com/83728702/162639327-6a4b63bc-6350-494f-bc32-71eee29bc1a6.jpg)

**Comment by PavlosTze** [comment]
@Pienio1981 What version do you have? You can find it in Settings.

**Comment by PavlosTze** [comment]
I'm closing this as these were some common bugs in previous versions that are now fixed.
