### ISSUE TITLE
[BUG] Total WXM Rewards calculated incorrectly - order of operations rounding issue

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#43]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The max amount earned per day currently is 103.23550724637681
When the daily earning is displayed with 2 places after the decimal, it's currently properly displayed as 103.24.
So far, the app has captured 6 days of payouts for my station.
6 * 103.23550724637681 = 619.41304347826086
When displayed with 2 places after the decimal, it should display as 619.41.
The 30 day view of rewards is properly adding up earnings transactions, then rounding to 2 decimal places, and displaying 629.41.
However, the Total earnings displayed for the weather station on the app home page appears to first round each individual transaction to 2 decimal places, then add the rounded numbers.
Currently, that means that the home page is showing Total earnings as 6 * 103.24 = 619.44 instead of the accurate amount of 619.41

### **How To Reproduce**
1. Collect multiple days of WXM rewards, but no more than 30 days.
2. Go to home page in the app
3. Notice "Total" WXM rewards for a weather station
4. Click on weather station, and scroll down to rewards section
5. Click "30D" to see total for last 30 days. Notice the amount is different.
6. Look at balance in MetaMask and confirm amount in the "30D" view is correct, and the Total amount on the homepage is incorrect (for this last step, you will need to use a weather station that did not receive the first two transactions that the app does not yet include in reward amounts)

### **Expected behavior**
The total rewards on the weather station on the app home page should only be rounded after adding up the detailed transactions.

### **Screenshots**
![Screenshot_20220414-033653.png](https://user-images.githubusercontent.com/70354350/163352016-a09ff440-d881-464f-b3db-5a619404f41e.png)
![Screenshot_20220414-033720.png](https://user-images.githubusercontent.com/70354350/163352045-6e0f696a-3a75-4474-9095-1aa4dfa6d73a.png)

### **Smartphone (please complete the following information that are needed for this bug):**
 - Android App Version 3.0.6-805d729

### **Additional context**
NOTE: although I haven't used the console recently, it is my understanding that similar functionality now exists in the console for some users. Any fix for this in the app should also be applied to similar functionality in the console.

Another way to likely observe the issue would be to collect several days of rewards, but no more than 7 days, and compare the home page Total to the 7D chart for the rewards.

**Comment by PavlosTze** [comment]
It's an API issue, probably something gone wrong in the rounding there. We are looking into it.

**Comment by PavlosTze** [comment]
Fixed @Greg15
