### ISSUE TITLE
[BUG] 2 Y-axis labels approach for small values can put top data point off chart and detail pop-up un-viewable

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#46]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
In some cases, the y-axis range is not including all the actual data points. Not only are some data points then not rendered in the visible portion of the graph, but clicking on the x-axis portion of the data point results in the detailed data pop-up not rendering in the visible part of the graph.

### **How To Reproduce**
1. Collect precipitation data identical to the data for 6-8pm UTC-5 on 12 April 2022 for Furry Golden Downpour (as shown in the screenshot - time shown in screenshot is UTC-5)
2. For the weather station, Click on 'See Historical Charts'
3. Scroll down to 'Precipitation' chart
4. Notice the data points for 6, 7 and 8pm are actually off/above the chart (notice that there is not a dark horizontal chart line connecting those readings - the vertical line for 6pm truncates at the top of the y-axis range, and the returning vertical line for the 8pm data point resumes - we have no idea how high the 6pm or 8pm data points are, not the in-between 7pm data point).
5. Then, click on the 7pm (UTC-5) data point. Notice that it displays the vertical black line for the x-axis value of data point being clicked, but notice that the horizontal black line showing the y-axis value of the data point does NOT display (because it's above the rendered area of the chart), and notice that the data point pop-up (which would show the exact value) does NOT display. I suspect the popup is being told to display ABOVE the  data point, which is outside the rendered section of the graph.

### **Expected behavior**
The y-axis range should include the full range of actual data points, and the detail data point pop-up should always render in the visible area of the chart.

### **Screenshots**
![Screenshot_20220416-084758.png](https://user-images.githubusercontent.com/70354350/163681477-14981cad-bd15-444f-b98b-63359a4b98a4.png)

### **Smartphone:**
- moto g(7) power
- Android version 10
 - Android App Version 3.0.7-483b2b1

### **Additional Context**
I suspect some of the same issue can happen with data points near the bottom of the y-axis range, for instance, if temp range stayed between 0.00°C and barely below -0.01°C

**Comment by PavlosTze** [comment]
@Greg15 Can you please remind me what Android device you have? I can't reproduce it (although I found a better fix on the precipitation chart for the Y labels), inputting your data shows everything correctly. 

So I suspect this might also be an Android/screen issue.

**Comment by Greg15** [comment]
- moto g(7) power
- Android version 10

I also updated the original issue with this info
