### ISSUE TITLE
Harvesting own weather data for DIY application

### ISSUE THREAD

**Issue by JeanSchoeller** [WeatherXM/issue-tracker#48]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Weather Station

### **Is your feature request related to a problem? Please describe.**
N/A

### **Describe the solution you'd like**

- Ability to easily send the weather data for DIY systems such as automated watering system via WiFi or LAN etc... without the need to expose any of the confidential informations (usr/pwd)

### **Describe alternatives you've considered**
Easy python package to communicate with the miner.

**Comment by PavlosTze** [comment]
Thank you for your suggestion! Our hardware for security reasons communicates only with our platform. The miner sends data to the IPFS and in the future we could facilitiate a way for the users to get access to their own data, and after that there may be built a public API where everyone could take their data.
