### ISSUE TITLE
Wind indicator initialization with compass

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#5]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Android Application
- M5 Firmware
- Weather Station

### **Is your feature request related to a problem? Please describe.**
Make weather station installation easier. Prevent false wind direction data 

### **Describe the solution you'd like**
Initialization function of the wind direction by aligning the arrow with a compass by locking it by hand until pressing  a button to create an offset stored in the app or miner to compensate with weather station real west

### **Describe alternatives you've considered**
Creating markers externally to the weather station on the side

**Comment by NikosTsiligaridis** [comment]
That adds unnecessary complexity both on the software side and on user installation, since there's already an arrow marking on the weather station pointing west which is aligned with the wind direction sensor's real west :)

**Comment by kkatsoulak** [comment]
The idea behind it is that the alignment should happen after installation. The marker you're referring is on top of the station and not easily visible when mounted on a pole on a roof and you're standing on a high ladder. 
Also some people would get an error when aligning due to the limitations of the weather station design and some others might even skip this step. (Can't remember when I did the installation if it was a necessary step that the software prompted you to do it)
The easiest might be to align the phone with north/south based on an diagram of the station that would much the installation (front and bottom looks different) and then calculate the offset internally in the app by polling GPS data from the phone

**Comment by PavlosTze** [comment]
Thank you for your suggestion. We will consider a mechanism that helps the installation process, but this cannot take place after the installation.

In the future we will have mechanisms that will validate the weather data of any given station, they will flag those stations and notifications will be sent to their owners that something is wrong (i.e. wrong wind direction).
