### ISSUE TITLE
[BUG] Total WXM rewards don't match in app and MetaMask wallet

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#52]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
The total of WXM token rewards in the app doesn't match the total in my MetaMask wallet. The app is showing 1 day's worth of max tokens less than what is in the MetaMask wallet.

### **How To Reproduce**
Check app total, check MetaMask total

### **Expected behavior**
App total and MetaMask total match

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/164334537-8e5ff6ad-53e9-4cd9-b734-53681579a0a2.png)
![image](https://user-images.githubusercontent.com/46647866/164334581-5959310a-1454-4d34-8bf1-1eacc62b638e.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
Device: Fire Tablet 7 (9th gen)
OS: Fire OS 7.3.2.2
Android App Version: 3.0.8-49c9f79

**Comment by PavlosTze** [comment]
@RevNotDev can you please let me know your Weather Station name? If you want you can send me a DM in Discord in private.

**Comment by kkatsoulak** [comment]
Also have the same problem. Precise brick degree

**Comment by PavlosTze** [comment]
We have identified the issue and looking into a fix.

**Comment by PavlosTze** [comment]
Fixed.
