### ISSUE TITLE
Download claimed station daily data for personal use

### ISSUE THREAD

**Issue by Basecracker** [WeatherXM/issue-tracker#53]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Weather Station 

### **Is your feature request related to a problem? Please describe.**
No problem.

### **Describe the solution you'd like**
It would be great if we could access our own claimed station(s) weather data, to be able to use for personal use. So I can create my own dashboards/weather data analysis, in programs like Excel/Power BI.  This would also be of particular interest to weather enthusiasts who purchase stations. A CSV download file or similar would suffice.

### **Describe alternatives you've considered**
Other automated weather stations on the market offer this data download functionality, but are not supported by this project at this time.

### **Additional context**
In particular, daily downloadable historical data would be of interest. So, for each calendar day;
 A single data recording for maximum/minimum temperature, daily rainfall total, max wind gust and direction, max pressure would probably cover the main variables.

**Comment by PavlosTze** [comment]
Thank you for your suggestion! The miner sends data to the IPFS and in the future we could facilitiate a way for the users to get access to their own data, and after that there may be built a public API where everyone could take their data.
