### ISSUE TITLE
[BUG] Wind speed graph has no y-axis label with only one data point

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#57]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
It is barely past midnight local time, so the graphs have just one data point. The wind speed chart has no y-axis labels for a windspeed and gust between 2 and 3 mph.

### **How To Reproduce**
1. Recreate data identical to the data for just past midnight local time 25 April 2022 (UTC-5) for the weather station in the screenshot
2. Look at historical charts, for today.
3. Notice that the wind speed graph has no y-axis labels.

### **Expected behavior**
At least 2 y-axis labels.

### **Screenshots**
![Screenshot_20220425-001717.png](https://user-images.githubusercontent.com/70354350/165025044-e4da1f45-c485-423f-b601-3f3ada6f117a.png)

### **Smartphone:**
 - Device: moto g7 power
 - OS: Android version 10
 - Android App Version 3.0.8-49c9f79

**Comment by Greg15** [comment]
I just realized that one thing that might the graph in question different from the rest of the graphs is that it's displaying 2 data sets in the graph - wind speed and gust speed.
Maybe having 2 things graphed is causing it to be the only graph missing y-axis labels when there is only a single data point for each line.

**Comment by PavlosTze** [comment]
Thanks for reporting that @Greg15 . This just got fixed in the latest beta release therefore I am closing this issue.
