### ISSUE TITLE
[BUG]Pressure missing Y-axis labels with narrow data range

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#58]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
2 data points of 29.31 inHg has no y-axis labels.

### **How To Reproduce**
1. Recreate the data as shown.
2. Loom at historical chart for pressure

### **Expected behavior**
Should have at least 2 Y-axis labels.

### **Screenshots**
![Screenshot_20220425-010218.png](https://user-images.githubusercontent.com/70354350/165029959-af468907-aa52-47fe-9466-c3238236406a.png)

![Screenshot_20220425-010311.png](https://user-images.githubusercontent.com/70354350/165029997-d15b10e4-a6da-4cc4-b9f8-fddfe90983e7.png)

![Screenshot_20220425-010253.png](https://user-images.githubusercontent.com/70354350/165030008-794e716e-1adc-46ff-a558-8889068aacfc.png)

### **Smartphone**
 - Device: moto g7 power
 - OS: android version 10
 - Android App Version 3.0.8-49c9f79

**Comment by PavlosTze** [comment]
@Greg15 Can't really reproduce it. Can you try again with a clean install please?

**Comment by Greg15** [comment]
I'll monitor to see if I can recreate the scenario under a fresh install, but it might be a long time.
I would need be up between 1am and 2am my time where the pressure remained almost literally constant for potentially over an hour.
I'm unlikely to stumble across that particular combination and be awake and check.

**Comment by Greg15** [comment]
Awesome. Sounds good. If I notice the bug again, I'll let you know.
I recognize that it's not ideal to let bugs remain open indefinitely when we don't know if they actually still are an issue, so I respect if it gets closed out on the basis that it might have been fixed, but no ability to confirm.

If it gets closed and I encounter it again, I can resubmit.

**Comment by PavlosTze** [comment]
@Greg15 Let's give it some days in case it can be reproduced by someone/somehow, and we will reconsider it again in the future. :)

**Comment by PavlosTze** [comment]
Thanks for reporting that @Greg15 . This just got fixed in the latest beta release therefore I am closing this issue.
