### ISSUE TITLE
[BUG] X-axis only has one value label when there are 2 data points

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#59]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
When there are only 2 data points, the x-axis only has one value label, and it's not quickly obvious that there's only 2 data points, so it takes a bit to look at the graph and recognize that it's representing a data point for just midnight and 1am. It's difficult to discern the x-axis scale without at least 2 labels on the x-axis.

### **How To Reproduce**
1. Use the app after 1am and before 2am
2. Click on See Historical Charts, and look at charts for 'Today'
3. See X-axis value labels

### **Expected behavior**
When there is more than 1 data point, there should be at least 2 labels on the x-axis to communicate the x-axis scale. 
I suspect that there are at least 2 x-axis labels for 4 or more days points, so I suspect the bug only exists for 2 and 3 data points.

### **Screenshots**
![Screenshot_20220427-012223.png](https://user-images.githubusercontent.com/70354350/165456172-75b802f8-5235-4d4a-bc50-65a6303d7e26.png)

### **Smartphone (please complete the following information that are needed for this bug):**
 - Android App Version 3.0.9-511ce1b

### **Additional context**
The scenario I encountered was with 2 days points. I am guessing the same issue applies for 3 data points, because I think the current graphs label every 4th data point on the x-axis.

**Comment by PavlosTze** [comment]
Thanks for reporting that @Greg15 . This just got fixed in the latest beta release therefore I am closing this issue.
