### ISSUE TITLE
[Change M5 Miner Device Name on Wi-Fi Network]

### ISSUE THREAD

**Issue by whenwhitepaper** [WeatherXM/issue-tracker#6]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:

- M5 Firmware

### **Is your feature request related to a problem? Please describe.**
WXM M5 Miner shows up as "Core2ForAWS" when connected to Wi-Fi network instead of the product name. 

### **Describe the solution you'd like**
The device should broadcast the name of "WXMMinerM5" or something similar to make it clear what the device is on the Wi-Fi network. A vendor name of "WeatherXM" should also be broadcasted. 

#### **Alternate names include**:
WXM M5
WeatherXM M5
WeatherXM Gateway
WeatherXM Miner
WXM M5 Wi-Fi Miner
![image](https://user-images.githubusercontent.com/100400250/155662055-be38de51-0a1b-4bf5-a8fa-134374d817c4.png)

**Comment by NikosTsiligaridis** [comment]
This is already fixed, you will receive it on the next update.
