### ISSUE TITLE
Network error while zooming

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#60]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
When you go to explorer when you zoom in by a lot, before loading the stations, it gets a network error. If you let it load the stations and then zoom in it's fine. It's as if after a certain zoom level the app stops communication with server.

### **How To Reproduce**
1. Go to explorer
2. Imidiately Zoom in to a high level before the stations load
3. See Network - error

### **Expected behavior**
Fetch data fast. Maybe use cashed data to display first and then do adjustments

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: [Mi10T Pro]
 - OS: [Android 11]]
 - Android App Version [3.0.9-511ce1b]

### **Additional context**
Other people managed to reproduce it. Maybe it's best to start explorer in a preset zoom level and fetch data for the displayed area first. When thousands of devices register it would take forever to load them all simultaneously.

###**Edit

![Screenshot_2022-04-30-22-38-35-258_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/166120272-94b0adee-af88-4c96-a686-ccb460f8c500.jpg)
![Screenshot_2022-04-30-22-37-56-428_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/166120278-be559d81-ca3c-43ba-8eee-f11061ed5e21.jpg)

After the error occurs data are not loaded even if you zoom out

**Comment by RevNotDev** [comment]
I reproduced this error on my Fire Tablet. I had to force stop the app after getting the error in order to get the stations to load again.

**Comment by PavlosTze** [comment]
Thanks for reporting that @kkatsoulak . This just got fixed in the latest beta release therefore I am closing this issue.
