### ISSUE TITLE
[BUG] Total WXM rewards on home page is incorrect under certain undetermined circumstances

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#61]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The WXM rewards on the homepage currently do NOT match the total rewards displayed on the 30 day view, nor in my metamask wallet. Note that the first transaction was within the last 30 days, so they should all match. The home page Total rewards is the real total rewards shown in the other 2 locations + the last earnings.

### **How To Reproduce**
1. Reconstruct the rewards history for Furry Golden Downpour, and look at it between 1am and 2am local time (UTC-5) on 3 May 2022
2. Look at the WXM rewards on the home page, on the 30 day history, and in the metamask wallet (or on the blockchain). Notice that the metamask/blockchain value and the 30 day value are the same (first reward was just under 30 days ago), but the home page Total is equal to the total plus the most recent reward value. 

### **Expected behavior**
The total on the home page should equal the total in MetaMask, and should equal the 30 day total when the first reward was no more than 30 days ago.

### **Screenshots**
![Screenshot_20220503-012251.png](https://user-images.githubusercontent.com/70354350/166413558-c198c245-0f58-4f2c-9d14-8fe5e398af57.png)

![Screenshot_20220503-012322.png](https://user-images.githubusercontent.com/70354350/166413614-95756736-2117-4316-a454-69a9ffb6bf2b.png)

![Screenshot_20220503-012528.png](https://user-images.githubusercontent.com/70354350/166413652-7e4ebbd9-7121-4dde-a306-3d218b8a9519.png)

![Screenshot_20220503-014531.png](https://user-images.githubusercontent.com/70354350/166414009-6bf44a81-4f34-4dcf-855a-01af3f38e50a.png)

### **Smartphone;**
 - Device: Moto G7 power
 -OS version: Android version 10
 - Android App Version 3.0.9-511ce1b

### **Additional context**
I have never seen this before, so it is possibly a boundary condition. The 24 hour rewards shown in the app right now are zero.

I suspect it is in the API, but I'll leave it to you to find the actual location of the issue.

**Comment by PavlosTze** [comment]
Thank you for that @Greg15 . Yes the issue looks like it's an API issue, we will investigate it further and report back.

**Comment by RevNotDev** [comment]
Total not matching 30day or MM for me either.
![image](https://user-images.githubusercontent.com/46647866/166587190-6b895634-e985-4559-9a54-4357c6f29a8d.png)
![image](https://user-images.githubusercontent.com/46647866/166587219-45ae1ed2-cccb-4786-8be3-01d0219765bc.png)
![image](https://user-images.githubusercontent.com/46647866/166587239-59151de8-cb88-478e-b267-ffe8701f9cdc.png)

**Comment by Greg15** [comment]
Ignoring rounding, it looks like for @RevNotDev the home page Total also equals the real total PLUS the last reward. That matches what I saw.

**Comment by tmavroeid** [comment]
This issue is currently fixed. However, it is expected to happen again until our new release which will solve it.

**Comment by Skallagrimmm** [comment]
@PavlosTze @tmavroeid hey guys, looks like I am also having this issue. The total on th homepage of the app is 103.61 more than metamask and the blockchain explorer..![Screenshot_20220516-212459.png](https://user-images.githubusercontent.com/100298772/168730107-36fb1c57-e23c-4d34-ae19-a2f0a2cd2e46.png)
![Screenshot_20220516-212824.png](https://user-images.githubusercontent.com/100298772/168730129-df6e17ac-743a-4955-a176-667ffd4aceb9.png)

**Comment by tmavroeid** [comment]
We are working on fixing this issue. Until the end of day, the total rewards in MM and in our systems will be in sync. Thank you for your feedback @Skallagrimmm .

**Comment by tmavroeid** [comment]
We have addressed this bug with our new release for the rewarding mechanism.
