### ISSUE TITLE
Race condition allows today's historical weather graphs to display as a prior day's graphs

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#62]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
There is a race condition, where if you click on a different day in the Historical Charts section before the initial charts for Today render, that Today's charts display, but with the heading and appearance of a different day

### **How To Reproduce**
1. Go to App mainpage
2. Click on a station name
3. Click on 'See Historical Charts'
4. When the page first starts loading, notice that the days will appear at the top of the screen, with 'Today' selected by default, even before any data is rendered. Also notice the days will be clickable, before the data for Today is rendered.
5. IMMEDIATELY click on any different day before the weather data graphs for today initially render (e.g., 'Yesterday'). Notice that the clicked day will be shown as selected.
6. Notice that when graph data finally renders, it will be today's data rendered, but with the other clicked day selected in the section header. 

### **Expected behavior**
The rendered data should match the day selected in the section header. In this case, the rendered data should match the day selected and highlighted in the section header.

### **Screenshots**
![Screenshot_20220510-171644.png](https://user-images.githubusercontent.com/70354350/167732579-dee7b908-496e-4aa3-be4c-9357b0d26f79.png)

### **Smartphone:**
 - Device: moto g7 power
 - OS: Android version 10
 - Android App Version 3.0.9-511ce1b

### **Additional Context**
You can actually click on multiple days in quick succession, as long as no graphs render, and you'll end up with today's graphs, displayed with the last clicked day.
I have not been able to confirm if there is also a similar race condition once graphs first render, and then I quickly click between multiple days.

**Comment by PavlosTze** [comment]
Thanks for reporting that @Greg15 . This just got fixed in the latest beta release therefore I am closing this issue.
