### ISSUE TITLE
Race condition allows today's forecast to appear as tomorrow's forecast, overriding already rendered tomorrow's data

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#63]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
A race condition allows me to request and get rendered tomorrow's hourly forecast data, but then the presumed page initialization of forecast data for today overrides it, but leaves the hourly forecast data labeled as tomorrow

### **How To Reproduce**
1. From app homepage, click on a weather station.
2. IMMEDIATELY before today's hourly forecast populates, Click on 'Tomorrow'
3. Notice that screen will immediately render tomorrow's hourly forecast, and that the big blue box will render with the details of the first hour of tomorrow forecast (this condition may require that you've already navigated here and cached tomorrow's forecast data)
4. Keep watching, and notice that the page quickly finishes loading *today's* weather data forecast (including changing the big blue box to display the details for right now), but that the selected day will still show 'Tomorrow'

### **Expected behavior**
The rendered data should match the selected day. In this case, the rendered data should be for 'Tomorrow', and the initial retrieve of today data should not override the already displayed data for tomorrow.

### **Screenshots**
![Screenshot_20220510-174633.png](https://user-images.githubusercontent.com/70354350/167736298-2c9c9985-514e-4b1f-a381-aaba7e05c6f1.png)

### **Smartphone:**
 - Device: moto g7 power
 - OS: android version 10
 - Android App Version 3.0.9-511ce1b

### **Additional context**
I also have run into a scenario where if I try this when I am within the last hour of today, the app stops
![Screenshot_20220510-232614.png](https://user-images.githubusercontent.com/70354350/167769191-69bdebe6-9f89-4fc0-bd65-94ba6d7b315c.png)

It might make sense to explore if there are other places these types of page initialization race conditions could occur, and see if a refactoring is needed to deal with all page initializations vs view changes initiated before default page data loads.

**Comment by PavlosTze** [comment]
We are in the process of redesigning this screen with an emphasis of the forecast part of it, so I'll leave this issue open until we finish this internally as we might go with another solution & UI here.

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
