### ISSUE TITLE
Historical Pressure chart uses too wide of a y-axis scale when inHg is used, but is fine when hPa is used

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#65]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The y-axis scale for Pressure is so wide when using inHg compared to actual values, that it's difficult to discern the amount of change over an hour. It appears the refactoring assumes the y-axis should use whole integers, which only makes sense for hPa, not inHg

### **How To Reproduce**
1. Change settings to use inHg for pressure
2. View a historical Pressure chart
3. Toggle settings to use hPa for pressure
4. View identical historical Pressure chart
5. Notice how easy it is to tell if the pressure was changing rapidly when using hPa, but not when using inHg

### **Expected behavior**
The y-axis scale should be appropriate for interpretation of graph data regardless of units chosen.

### **Screenshots**
![Screenshot_20220512-131322.png](https://user-images.githubusercontent.com/70354350/168143878-720d4e48-8af0-4451-b0a0-27de995393b5.png)
![Screenshot_20220512-131401.png](https://user-images.githubusercontent.com/70354350/168143908-8143e4d0-e4d3-42f6-beeb-882c2bcefd8e.png)

### **Smartphone:**
 - Device: moto g7 power
 - OS: Android 10
 - Android App Version 3.1.0-3a64cd1

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
