### ISSUE TITLE
7 day Forecast temp range bars don't line up

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#66]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
This is a very minor thing that I noticed, it may not concern you at all, but because I noticed it I thought I might as well log it just in case. The blue temperature range bars in the 7 day forecast don't line up when they're ranging from or to the same temperature. 
The screenshot included will explain it best looking at the low of 10 degrees and high of 18 & 20 degrees. 

### **How To Reproduce**
Look at the 7 day forecast

### **Expected behavior**
The blue bars line up when ranging from or to the same temperature.

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/168173715-83e41912-f7aa-4c58-9560-01d2ca4a608b.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
This looks the same on Bluestacks and on my Fire Tablet 7.
Device: Fire Tablet 7 (9th gen)
OS: Fire OS 7.3.2.2
Android App Version: 3.1.0-3a64cd1

**Comment by Greg15** [comment]
I wonder if the blue bars are based on scaling non-rounded temperature forecasts, but the numbers for low and high temps are displayed after rounding the forecast to the nearest integer. If that is the case, I would agree that the UX would be improved if the bars were consistent with the displayed numbers, so round all the lows and highs and then scale the blue bars based on the rounded displayed numbers. Even if the current approach technically is a more accurate range for non-rounded numbers, I agree that it causes confusion.

**Comment by RevNotDev** [comment]
Another great example I saw today
![image](https://user-images.githubusercontent.com/46647866/168676570-3f74c7ca-1eee-4f59-95e5-1a80f48418f1.png)

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)

**Comment by RevNotDev** [comment]
I think the fix has made it worse 
![image](https://user-images.githubusercontent.com/46647866/170023179-8d9fdc13-776b-43cf-ac21-017f50d9da39.png)

**Comment by PavlosTze** [comment]
@RevNotDev We have just released a new beta version which addresses this issue. Hopefully this resolves the issue at last. Please have a look. I am closing this and if the issue persists please let me know.

Thank you! :)
