### ISSUE TITLE
7 Day forecast sometimes shows 8 days

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#68]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
During the final part of a day (at least for me during the last hour at UTC-5, before midnight) the 7 day forecast shows today AND the next 7 days (8 days total) but just after midnight, it shows 7 days.

### **How To Reproduce**
1. Wait until 11:50pm local time
2. Go to 7 day forecast. Notice there are 8 days listed.
3. Wait until after midnight, and return to 7 day forecast. Notice there are 7 days listed again.

### **Expected behavior**
A section called 7 day forecast should probably show 7 days. I appreciate that if it's truncated to "7 days" under this scenario and one of those days is today, it's really only going to show me 6 days plus a few minutes until midnight arrives, and that's not as useful as a full 7 days when attempting to plan. So 3 additional options...

(Less ideal) Although the page header says 7 day forecast, the label to click to get there says "Next 7 days". Maybe the page should only show the 7 days after today.

(More ideal) maybe the 7 day forecast should include today until a certain threshold (such as at least 1 hour left in the day). But once that threshold is crossed, today shouldn't be included in the 7 day forecast, even if today is not over, and then the subsequent 7 days should be shown.

 (in the middle) Change it to 10 day forecast, and make sure it always only shows 10 days, and the first day of those 10 is always today, even if there is only 10 minutes left in the day. But that would possibly require a 10 day forecast to be reasonably useful, and maybe forecast accuracy drops off rapidly after 7 days.

### **Screenshots**
![Screenshot_20220514-235134.png](https://user-images.githubusercontent.com/70354350/168459249-9310bbcb-89af-474d-9769-6ed197f22e46.png)
![Screenshot_20220515-003041.png](https://user-images.githubusercontent.com/70354350/168459253-9c450aef-2d5f-4946-a392-d0d64fe89822.png)

### **Smartphone:**
 - Device: moto g7 power
 - OS: android version 10
 - Android App Version 3.1.0-3a64cd1

**Comment by RevNotDev** [comment]
Just noticed I have 8 days showing too
![image](https://user-images.githubusercontent.com/46647866/168676885-8bf05ffd-e92c-4fb5-b812-aff4174f0d6b.png)
