### ISSUE TITLE
Wind Gust value on M5 not matching historical charts data

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#69]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application
- M5 Firmware

## **Describe the bug**
Today at around 7:45pm I heard some strong winds outside, so I checked the M5 and it said 37.5mph for 'Gust' speed. This is the highest reading I've seen for wind gust so far. When checking the historical charts later on, the highest wind gust it showed was 13.2mph.

### **How To Reproduce**
Check 'Gust' speed on M5 and compare against historical charts data.

### **Expected behavior**
M5 'Gust' speed to match the historical charts data.

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/168924001-376b0d76-001d-4cc6-8386-b8bdf8c12803.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
This looks the same on Bluestacks and on my Fire Tablet 7.
Device: Fire Tablet 7 (9th gen)
OS: Fire OS 7.3.2.2
Android App Version: 3.1.0-3a64cd1

### **If Applicable: M5 (please complete the following information):**
 - Firmware Version 0.3.11

**Comment by Greg15** [comment]
I went and checked mine as well. Same thing. And, I noticed a related item, where the current wind speed on the M5 can also differ a lot from the current wind speed on the Now weather tile in the app. The M5 can show a much higher current wind speed.

**Comment by PavlosTze** [comment]
This is a known issue as on the historical charts we use `average` aggregation (which is a bug) instead of `max`. A fix is pending for that.

**Comment by Greg15** [comment]
Awesome. It's one of the 2 areas so far that have concerned me the most, so I will love to see this one improved.

**Comment by PavlosTze** [comment]
Hello @RevNotDev and @Greg15 . This should be fixed, we released a new API version that handles this and uses `MAX` aggregation for wind gust. Can you please confirm?

**Comment by Greg15** [comment]
I'll see if I can take a unit for a drive in the car today to generate a high gust speed and check it

**Comment by Greg15** [comment]
I took a station for a short drive. Max gust seen on M5 was 41.1 mph. Historical chart in app has same value. Seems fixed to me. Thank you! 

This is the hyperlocal value I wanted to be able to check when away from my home for lengthy periods to see if wind speeds got high enough that I might need to go home to check for possible wind damage, so I appreciate this change.

![Screenshot_20220831-201723.png](https://user-images.githubusercontent.com/70354350/187812066-297c2bab-9b3b-405d-8dc2-e8ddec60fc78.png)

**Comment by PavlosTze** [comment]
That sounds great! Thank you for your help! :)
