### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dazzler99** [WeatherXM/issue-tracker#7]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website
- Android Application

WXM Station only visible in App, not in explorer.

### **How To Reproduce**
If you open the explorer in the android app, the station is visible, but if you look on https://weatherxm.com/explorer it ain`t.

### **Expected behavior**
To see in App and on explorer the station

### **Screenshots**

![20220225_104718](https://user-images.githubusercontent.com/100411296/155693837-9242af29-08b8-4a84-87d6-b2ceab2d215f.jpg)

![Screenshot_20220224-214443_WeatherXM](https://user-images.githubusercontent.com/100411296/155693843-d63db2dd-93b0-414a-ab0e-a7d27b6ec845.jpg)

### **If Applicable: Desktop (please complete the following information):**
 - OS Windows
 - Browser Chrome

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: SGS 21 Ultra
 - Android App Version 3.0.2-21c4a34

**Comment by PavlosTze** [comment]
We are looking into it @Dazzler99

**Comment by PavlosTze** [comment]
Fixed.
