### ISSUE TITLE
Today/Tomorrow forecast elements not lining up

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#70]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
In the Today and Tomorrow forecast multiple elements don't line up. Some boxes appear to have elements pushed down slightly. This includes the rain level, time, and the bottom edge of the box.

### **How To Reproduce**
Look at the Today and Tomorrow forecast

### **Expected behavior**
All the elements within the Today and Tomorrow forecast section to line up with each other.

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/170030606-0767910c-4ebd-4e9f-b2bf-6fed491b3878.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
This looks the same on Bluestacks and on my Fire Tablet 7.
Device: Fire Tablet 7 (9th gen)
OS: Fire OS 7.3.2.2
Android App Version: 3.1.1-f0f4bef

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
