### ISSUE TITLE
Pressure when using inHg seems to round too much, producing misleading historical charts

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#72]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The shape of historical charts for Pressure look very different when units are changed from hPa to inHg. It appears to round to nearest 0.1 inHg, which appears to be too big of a rounding to maintain an informative representation of how pressure was changing

### **How To Reproduce**
1. Display historical Pressure chart with hPa selected
2. Display the same historical Pressure chart with inHg selected
3. Compare

### **Expected behavior**
I expect the inHg graph of pressure to still maintain a better representation of the rate of change of pressure, similar to the graph shape when hPa is used. Perhaps rounding to nearest 0.01inHg would be far better.

### **Screenshots**
![Screenshot_20220525-234020.png](https://user-images.githubusercontent.com/70354350/170418687-b031ac72-b3f4-4942-8352-a078187c064e.png)
![Screenshot_20220525-234059.png](https://user-images.githubusercontent.com/70354350/170418704-7e8ce688-3ecd-417f-8e91-1ab6e51cf193.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: moto g7 power
 - OS: Android
 - Android App Version 3.1.1-f0f4bef

### **Additional context**
This bug likely appeared 2 beta versions ago, but the y-axis range was so large for Pressure when inHg was selected, that I couldn't see this until this most recent beta app update that fixed the y-axis range when inHg is selected.

Changing it to 2 decimal places in historical charts might then also require showing 2 decimal places on the station weather tile, for consistency purposes.
The app shows a single decimal for hPa in the station weather tile, but a single decimal for hPa is a much smaller pressure change than a single decimal of inHg.

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)

**Comment by Greg15** [comment]
The chart now looks great. Thank you. Is there a need to also change the current weather to also have 2 decimal places for pressure when units are mmHg? If the team has evaluated it and decided the answer is no, that's fine. I'm just asking out of an abundance of caution, to make sure every aspect was looked at.

**Comment by Greg15** [comment]
Yes, my bad. I meant inHg. And it is now displayed everywhere with 2 decimal places. It was perhaps a cache issue, but I can't know for certain because I'm just now checking, and it "self corrected" in the meantime. Thanks!
