### ISSUE TITLE
In-app explorer truncates bottom weather station in long list

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#73]
## WeatherXM Related Element
- Website
- Android Application

## **Describe the bug**
Via the in-app explorer, when clicking on a hex with weather stations, the user is presented a list of stations in that hex. If there are more than 3 stations, only the first 3 display on screen initially by default, and the user must scroll down to see the rest. When that happens, after scrolling all the way to the bottom of the list, the bottom station is slightly truncated.

### **How To Reproduce**
1. Go to the in-app explorer
2. Drill down to either the (0,0) hex in the ocean, or to the Athens, GR hex (both have more than 3 stations).
3. Click on the hex to get the list of stations
4. Scroll down to the bottom of the list and notice the slight truncation of the bottom of the display block of the last weather station.

### **Expected behavior**
The display block for the bottom station in the list should fully display, just like the rest.

### **Screenshots**
![Screenshot_20220526-234542.png](https://user-images.githubusercontent.com/70354350/170632589-19ac481f-b69c-4f45-b8a0-d8c4f3d715f8.png)

### **Smartphone:**
 - Device: moto g7 power
 - OS: android version 10
 - Android App Version 3.1.1-f0f4bef

### **Additional context**
The website explorer was not working for me, so I could not confirm if same behavior occurs in the website explorer as well.

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
