### ISSUE TITLE
Every station in in-app explorer reports as "last seen just now" whether online or offline, and regardless of how long it's been since weather data was provided

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#75]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
In the in-app explorer, every station says "last seen just now", even if it's offline or the data hasn't been updated in days.

### **How To Reproduce**
1. Go to in-app explorer
2. Click on any hex that has stations that are online but haven't been updated in days, and/or has offline stations (Athens, GR and the (0,0) hex in the ocean are good for this)
3. Notice that all stations in the list say "last seen just now"

### **Screenshots**
![Screenshot_20220527-002458.png](https://user-images.githubusercontent.com/70354350/170636208-a9117473-d406-4bc3-b814-66231e7ce7b7.png)

### **Smartphone:**
 - Device: moto g7 power
 - OS: android version 10
 - Android App Version 3.1.1-f0f4bef

### **Additional context**
It appears to be an API issue to me.
The same issue seems to exist on my in-app list of claimed stations. If the station is offline for hours, it still says "last seen just now".
I could not get the website explorer to work to see if it has the same issue there.

**Comment by PavlosTze** [comment]
This is a [known issue](https://github.com/WeatherXM/issue-tracker/issues/26), already being worked on and fixed in dev. A bug in a variable breaks the `online` and `last seen` indicator. Will be out in a next backend release :)

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)

**Comment by Greg15** [comment]
It appears to be unresolved
![Screenshot_20220630-225254.png](https://user-images.githubusercontent.com/70354350/176820212-66c3a4df-3f70-43a2-bf7a-8c090e8a3f39.png)

**Comment by PavlosTze** [comment]
@Greg15 Actually I found _after_ the beta release another bug on that text. Which has been fixed and seems to be finally OK now. So let's keep this issue as closed and have a look at it again on the next beta release.
