### ISSUE TITLE
Leaving and Returning to in-app explorer resets and zooms into last hex actually clicked on, rather than last location viewed and last zoom level viewed

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#77]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
There are multiple ways to zoom in on a hex. One is by clicking on a hex. One is by using 2 fingers to zoom in.
When revisiting the in-app explorer, it returns to last hex clicked on, rather than last viewed location and last viewed zoom level. It only knows the last "exploration" as the last hex zoomed into using an actual click, and is not aware of any subsequent "exploration" to scroll around, to use 2 fingers to zoom out, or use 2 fingers to zoom in rather than clicking on a hex to zoom in.

### **How To Reproduce**
1. Close/exit the app and relaunch
2. Click on the in-app explorer
3. Notice that it defaults to Greece with bigger hexes
4. Scroll to a different part of the globe, such as Iceland
5. Click on the Iceland hex, to zoom in and see the smaller hex(es) that have an actual station. Don't just zoom in to the smaller hex(es) by using 2 fingers on the screen. Actually click on the larger hex.
6. Use 2 fingers on the screen to zoom back out, then scroll to another place such as somewhere in Canada that has a large hex.
7. Without clicking on a large hex, instead use 2 fingers to zoom in on a large hex until you can see the smaller hex(es).
8. Switch to Home or Settings.
9. Switch back to in-app explorer.
10. Notice that the in-app explorer re-centers and re-zooms to the last hex that you actually clicked on, regardless of where you had last scrolled to or zoomed into without clicking.
11. Now zoom back out using 2 fingers and navigate to another area, but do not zoom in
12. Switch to Home or Settings
13. Switch back to in-app explorer
14. Notice the in-app explorer re-centers and re-zooms to the last hex you actually clicked on.

### **Expected behavior**
When revisiting the in-app explorer, I expected the in-app explorer to remember the zoom level and location that I was on before I navigated to the home page or settings page.

### **Smartphone:**
 - Device: Moto G7 power
 - OS: Android version 10
 - Android App Version 3.1.1-f0f4bef

### **Additional context**
The current behavior is the most unexpected when after clicking on a large hex to see small hexes in it, you then zoom out, scroll elsewhere, and zoom in to see smaller hexes using 2 fingers without clicking, and then click on a small hex to see a list of stations and click on a station to see the weather. When going back to home or settings and then returning to in-app explorer, it still only remembers the last LARGE hex clicked on, and doesn't return to the location of the small hex clicked on.

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
