### ISSUE TITLE
Units for precipitation in App appear to be incorrect 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#78]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The current "now" weather tile indicates by the units that it is displaying the *amount* of precipitation (in or mm). But in fact, I think it's really displaying the instantaneous *rate* of precipitation (in/hr, mm/hr) rather than the *amount* of precipitation.
On the hourly forecast tiles, it's not clear if a value of 0.5in means that 0.5 inch of rain is forecasted during that hour, or if the forecasted max instantaneous rate of rain is 0.5in/hr.
Similarly, for precipitation chart under "See Historical Charts" button, the y-axis is labeled as amount of precipitation (in or mm), but I suspect that it's indicating the avg instantaneous rate of rain during that hour. The distinction is especially important when looking at the chart for the current hour during a rainstorm and we're only a few minutes into the hour. 1in/hr of rain for the first 5 minutes is way different than 1in of rain *within* the first 5 minutes. The latter is actually an instantaneous rate of 12in/hr, which is quite a downpour!

### **How To Reproduce**
1. Go to in-app current weather tile during a rainstorm.
2. Periodically refresh the page
3. Notice that within a single hour, the "precipitation" value can go up and down (including down to zero). Also notice that in reality, actual precipitation in an hour cannot go down to zero once any precipitation has occurred in that hour. Actual inches of precipitation can only stay the same (if raining stopped) or increase. Only the "rate" of precipitation can go back down to zero during that hour.

### **Expected behavior**
The units displayed should be accurate.  Since I'm not sure what is actually being displayed in each place, I can only point out that what's there seems incorrect.
Actual precipitation should be measured in inches or mm, but rate of rain should be measured in inches/hr or mm/hr.

### **Screenshots**
![Screenshot_20220603-183516.png](https://user-images.githubusercontent.com/70354350/171968063-d0426c01-0d49-4b92-ad0e-d1233fd439ba.png)
![Screenshot_20220603-183602.png](https://user-images.githubusercontent.com/70354350/171968070-7e00ea0f-ab62-4caf-859f-43aaeb747433.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: moto g7 power 
 - OS: android version 10 
 - Android App Version 3.1.1-f0f4bef

### **Additional context**
I have not looked at the M5 interface or the console to see if similar issues exist in those places. Presumably, this affects the same "now" weather display in the in-app explorer for a station and in the website explorer for a chosen station.

I recognize that the long term solution might not just be changing the labels, but also possibly changing calculation of what value is displayed and how it is calculated.

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
