### ISSUE TITLE
Append Time Zone Abbreviation Next to Displayed Time in App

### ISSUE THREAD

**Issue by EmperorDRT1** [WeatherXM/issue-tracker#79]
### WeatherXM Related Element

- Android Application
### **Is your feature request related to a problem? Please describe.**
If a user owns stations located in different time zones, it may not be immediately apparent that the time displayed for a station is based on the time zone of that station's location rather than the user's current time. At first glance, a user may think a station is one or more hours delayed if their own time zone differs from that of the station they are viewing, which could cause concern. 

### **Describe the solution you'd like**
Append the time zone abbreviation next to the displayed time in the app.

**The time zone abbreviation could be appended conditionally:**

- If the user owns more than one station separated by time zones, the time zone abbreviation would be appended

- If the user "follows" more than one station separated by time zones, the time zone abbreviation would be appended (assuming that the ability to "follow" a station is implemented)
### **Describe alternatives you've considered**

**An icon and respective tooltip could be used:**

Instead of appending the time zone abbreviation next to the time, there could instead be an icon next to the time with a tooltip popup of the time zone when tapped. This would result in a more elegant solution for time zones that don't have their own time zone abbreviation but rather a UTC offset. It could also be used as a way to provide extra information about a time zone abbreviation (e.g. US CST vs CN CST).

### **Additional context**

Current behavior of the displayed current time of two stations in different time zones:
![image](https://user-images.githubusercontent.com/44149620/172216835-acd5d158-0d48-4eea-8729-09c93ff40eb4.png)
![image](https://user-images.githubusercontent.com/44149620/172216849-f1446661-b1f2-48f3-a922-010cdd08fcdf.png)

Requested behavior of time zone abbreviation next to displayed time:
![Screenshot 2022-06-06 124914-1](https://user-images.githubusercontent.com/44149620/172222860-1edcd77a-56e7-4e4c-8308-cfd15c4b0200.png)
![Screenshot 2022-06-06 124858-1](https://user-images.githubusercontent.com/44149620/172222857-48d76e56-4242-416e-814e-654542e414ad.png)

Alternative solution of icon next to displayed time with respective tooltip when tapped:
![Screenshot 2022-06-06 124858-2](https://user-images.githubusercontent.com/44149620/172229053-2233815c-2773-4a81-a3a8-3585a9362499.png)

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
