### ISSUE TITLE
Negative pressure spikes on web dashboard

### ISSUE THREAD

**Issue by 1810alex** [WeatherXM/issue-tracker#80]
## WeatherXM Related Element
- Web Dashboard

## **Describe the bug**
Negative pressure spikes can be observed approx 100 hPA on the pressure graph when the data intervals are set to anything less than 2 hrs.

### **How To Reproduce**
1. Go to web dashboard
2. Click on time settings top right
3. Set interval to 5min
4. Observe pressure chart

### **Expected behavior**
I don't believe these drops are real as that would be an equivalent of an instantaneous gain of 3000ft altitude.

### **Screenshots**
<img width="588" alt="Screenshot 2022-06-08 at 15 30 22" src="https://user-images.githubusercontent.com/98117905/172650270-cf514563-1b91-4ddc-9f00-173cc079cc41.png">

### **If Applicable: Desktop (please complete the following information):**
 - Version [e.g. 3.0.0]

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Macbook & iPhone 13 Pro
 - OS: macOS Monterey 12.4, iOS 15.5
 - Browser Safari + Firefox (Mac), Safari (iOS)

### **If Applicable: M5 (please complete the following information):**
 - Firmware Version 0.3.22

**Comment by NikosTsiligaridis** [comment]
Hi
Please send me your s/n or station name on discord.

**Comment by RevNotDev** [comment]
Just to add to this, I'm seeing some strange dips on the pressure readings on one of my stations too. Not quite as severe as the ones above though. 
![image](https://user-images.githubusercontent.com/46647866/179842497-85ef64a8-bf1a-47ef-9656-50b1c0725f32.png)
![image](https://user-images.githubusercontent.com/46647866/179842632-d5e22a89-c36a-47f0-ac3b-47af5e85821d.png)

**Comment by NikosTsiligaridis** [comment]
This is a known issue to be fixed in the next update :)
