### ISSUE TITLE
Double testnet rewards on day 1 (April 6th)

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#82]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

In the Android app under Detailed WXM Rewards April 6th is rewarded twice, not sure if this has been dealt with or not.

### **How To Reproduce**

1. Go to 'Android App"
2. Click on Detailed WXM Rewards"
3. Scroll down to April 6th
4. See two entries for that date.

### **Expected behavior**
One reward transaction per day.

### **Screenshots**

![Screenshot_20220616-214601~2.png](https://user-images.githubusercontent.com/100298772/174227610-47105afe-3c7d-4fb9-9958-c2c7d23643ab.png)

### **If Applicable: Desktop (please complete the following information):**
 - OS: [e.g. Android]
 - Version [e.g. 3.1.1-f0f4bef]

**Comment by PavlosTze** [comment]
Because of an internal bug we had the previous days because April 6th, we made two transactions on that day with the one being a reimbursment one. Therefore this isn't a bug. Thank you though for noticing that. :)
