### ISSUE TITLE
Wind speed is null

### ISSUE THREAD

**Issue by jsloane** [WeatherXM/issue-tracker#89]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
The wind speed in the Android app shows as "nullkm/h" and the wind charts have no data.
The wind speed does show on the explorer website however.

### **How To Reproduce**
1. Open weather station details, observe wind speed and see error.
2. Click on historical charts 
3. Scroll down to wind chart
4. See missing data

### **Expected behavior**
Expect to see wind speed data.

### **Screenshots**
![image](https://user-images.githubusercontent.com/186535/176038903-b0371501-72ad-48aa-8fd7-2adb59af4627.png)

![image](https://user-images.githubusercontent.com/186535/176038951-cc161bf1-4329-42e8-85b2-fe90a069febb.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Samsung Galaxy S21
 - OS: Android 12
 - Browser
 - Android App Version: 3.1.2-f886e20

**Comment by PavlosTze** [comment]
I have seen some other weird data on these screenshots @jsloane . Can you please try to delete the app and re-download it and send a screenshot again? Thank you.

**Comment by jsloane** [comment]
@PavlosTze that fixed the issue in both places.
![image](https://user-images.githubusercontent.com/186535/176058952-864f6021-888c-4b1e-b96b-3adbfefd1125.png)

**Comment by PavlosTze** [comment]
Great! Thank you :)
