### ISSUE TITLE
Ability to zoom all the way out in explorer

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#9]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Website
- Android Application

## **Describe the bug**
I can't zoom all the way out to see the entire world in view. It is still cropped in at maximum zoom out.

### **How To Reproduce**
1. Go to explorer on either the android app or website
2. Try and zoom all the way out so the whole world is in view

### **Expected behavior**
Expect the map to zoom all the way out so the entire world is in view.

### **Screenshots**

![Screenshot 2022-02-25 143746](https://user-images.githubusercontent.com/46647866/155734272-62ca37d9-6aaf-4f34-b6e6-5c7d47f22c4b.jpg)
![Screenshot 2022-02-25 144101](https://user-images.githubusercontent.com/46647866/155734276-4858908c-9330-47ff-b620-1b3c8cba302f.jpg)

### **If Applicable: Desktop (please complete the following information):**
 - OS: Android and Windows
 - Browser: Chrome
    - Version: 98.0.4758.102

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Fire Tablet 7
 - OS: Fire OS 7.3.2.2
 - Android App Version: 3.0.3-3f653e9

**Comment by PavlosTze** [comment]
Fixed.
