### ISSUE TITLE
Rewards section visually cuts off part of a number

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#91]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
On the new Rewards tile, the least significant digit of the "All" count is partially cutoff. In my circumstance, the rewards exceed 7000, so have 6 digits, including 2 after the decimal point. The issue might only appear for stations with over 1,000 or 2,000 WXM. In addition, the interface should be tested for the scenario of a user having over 10,000 and 100,000 WXM

### **How To Reproduce**
1. Go to App home page
2. Click on a weather station 
3. Scroll down to Rewards section 
4. See last digit of All truncated

### **Expected behavior**
The entire amount should appear regardless of how 'long' the number is

### **Screenshots**
![Screenshot_20220627-101044.png](https://user-images.githubusercontent.com/70354350/176295388-262c4d84-5d61-4f09-8e17-5960d7a4e33e.png)

### **Smartphone:**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version: 3.1.2-f886e20

### **Additional context**
None (love the new rewards section!)

**Comment by RevNotDev** [comment]
It's interesting how things scale on different devices. I can't check on my Fire Tablet as it crashes on signing in on the new beta, but on the Bluestacks emulator, this rewards section looks like this for me:
![image](https://user-images.githubusercontent.com/46647866/176310140-826a72fa-d14b-45a8-a6ba-23e683bdc79e.png)

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
