### ISSUE TITLE
Hourly Forecast slider jumps back to current time after 12am. 

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#92]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

If you scroll the hourly forecast slider and you cross the threshold into "tomorrow" or past 12am and then try and slide back to 11pm, 10pm and so on, the hourly slider jumps back to current time.

### **How To Reproduce**
1. Go to a weather station homepage 
2. Scroll down to the hourly forecast 
3. Swipe to past 12am and into "tomorrow"
4. Swipe back to 11pm and notice it will jump back to current time.

### **Expected behavior**

Should be able to smoothly scroll back and forth across the 11pm/12am threshold.

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: [e.g. Google pixel 2
 - OS: [e.g. android 11
 - Android App Version [3.1.2-f886e20],

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
