### ISSUE TITLE
The UV index historical graph has an issue

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#94]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
When the UV index for the entire graph period is zero, the horizontal chart lines are darker (black) in the UV chart than the horizontal lines (gray) in all other charts. In addition, the graph line for actual zero value data points aren't drawn. The combined graphing effect appears to indicate that the UV index was a horizontal value of 1 for the entire duration, rather than the accurate indication that the UV index was a Zero for the entire duration. I don't have a proposed solution, but perhaps just making the horizontal value line(s) the same faded grey as other graphs, instead of black, would be sufficient.

### **How To Reproduce**
1. after midnight (a new day, assuming it is dark at midnight), but before UV index rises above zero, go to the "See Historical Charts"
2. Observe the UV index chart
3. Notice that the horizontal graph lines are black, compared to gray for the other charts, and notice that this has the observer incorrectly believe that the darkened horizontal line is the actual UV Index line, and notice that there is no obvious indicator that the actual UV index bar or line chart has a value of zero 

### **Expected behavior**
Even when the UV index is zero throughout the graphing period, it should be consistent and clear what the graph value is

### **Screenshots**
![Screenshot_20220629-035454.png](https://user-images.githubusercontent.com/70354350/176399015-3713366d-6202-491c-b0ab-88b1ea1b3119.png)
![Screenshot_20220629-035515.png](https://user-images.githubusercontent.com/70354350/176399287-2fc85b3d-73e8-4a45-b0bd-ff9393329737.png)

### **Smartphone:**
 - Device: Moto g7 power 
 - OS: android version 10 
 - Android App Version: 3.1.2-f886e20

### **Additional context**
None (I am loving the enhancements overall - great job)

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
