### ISSUE TITLE
Add time to transactions on "Detailed WXM Rewards" page

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#95]
### WeatherXM Related Element
- Android Application

### **Describe the solution you'd like**
Now that local time is displayed in the Rewards chart for the most recent reward transaction, I believe it will be informative to display the local time for each transaction in the "Detailed WXM Rewards" list. This will be especially useful anytime there is a back-end bug that results in time delayed reward transactions.
![Screenshot_20220629-041846.png](https://user-images.githubusercontent.com/70354350/176402011-1232ad10-8693-47a2-966a-ed773a152ee2.png)
![Screenshot_20220629-042501.png](https://user-images.githubusercontent.com/70354350/176402234-db995c88-801e-44b4-a5ea-eb6a926839f5.png)

### **Describe alternatives you've considered**
None

### **Additional context**
None

**Comment by PavlosTze** [comment]
We just released a new beta version which includes this suggestion. Therefore I am closing this.

Thank you! :)
