### ISSUE TITLE
7 Day Forecast shows 8 days

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#96]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

As of 22:15 hours local time. The 7 day forecasts for my stations show 8 days...the current day which only has 2 hours left, and 7 full more days.

### **How To Reproduce**
1. Go to a weather station homepage 
2. Click on 7 Day Forecast 
3. See 8 days forecasted

### **Expected behavior**

Show only 7 days of forecasts.

### **Screenshots**

![Screenshot_20220629-221119.png](https://user-images.githubusercontent.com/100298772/176598678-9c0f321e-b5a2-4f38-b806-4d9120a458eb.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Google Pixel 2 
 - OS: Android 11
 
 - Android App Version 3.1.2-f886e20

**Comment by RevNotDev** [comment]
Can confirm, mine also shows 8 days currently.
![image](https://user-images.githubusercontent.com/46647866/176959805-1e7d50f8-b8da-4b4e-9929-bd97e2e2feb0.png)

**Comment by eeVoskos** [comment]
Thanks for reporting this @Skallagrimmm. I really think the app here works as expected! It's not unexpected to see, in a typical "7-day-ahead forecast screen" in weather apps, 7 or 8 days depending how close you are at the end of the current day and on the forecast service you are using.

Our - newly built - UX team is researching the redesign of the app and will be back in the future on how we display weather forecast. In the meanwhile, I'm closing this.
