### ISSUE TITLE
Possible inconsistency in max rewards indicator over last 7 or 30 days

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#97]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The new max line on the rewards chart shows a possibly misleading value. The actual max for the last 7 days was 29.104187946884576

The detailed rewards list shows that as 29.10

The chart shows a max line of 29.11

I realize that the line might be intended as a reference line in a chart.(similar to how graph lines might be chosen in historical weather data graphs) and not necessarily the actual highest amount of rewards during the selected time period. But when I look at it, my first assumption is that the line indicates the max rewards amount during the displayed data range. As such, I expect it to use rounding in the same way that the detailed transactions rounds.

### **How To Reproduce**
1. Go to station details page
2. Observe max/reference line value
3. Look at detailed transactions and see a possible different max than the max/reference line in the chart

### **Expected behavior**
I think seeing the same max value is more intuitive 

### **Screenshots**
![Screenshot_20220630-041021.png](https://user-images.githubusercontent.com/70354350/176639355-d3f5b164-f016-454d-860d-f4160aa893fa.png)
![Screenshot_20220630-041100.png](https://user-images.githubusercontent.com/70354350/176639412-f0b1a5ee-7fee-4c34-9f6c-a73abb7de430.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: moto g7 power 
 - OS: android version 10 
 - Android App Version: 3.1.2-f886e20

### **Additional context**
N/A

**Comment by Greg15** [comment]
For the 30 day value, the max/reference line isn't higher than the rounded value of the max amount.
Actual max: 103.61090909090909
Rounded amount in transaction details: 103.61
Max/reference line in rewards chart: 103.61

**Comment by PavlosTze** [comment]
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)
