### ISSUE TITLE
Unit Shows Offline in explorer, but M5 is all green.

### ISSUE THREAD

**Issue by vicpylon** [WeatherXM/issue-tracker#98]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
"Acrobatic Flint Anemometer" has been reported offline in the explorer for the past 6 hours. M5 unit shows all green and shows connection to the external sensor.

### **Expected behavior**
The unit should report to the explorer.

### **Screenshots**

![image](https://user-images.githubusercontent.com/35160110/177019560-34502342-9d0a-4042-a622-970ab7cdb4cf.png)

### **If Applicable: Desktop (please complete the following information):**

N/A

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
N/A

### **If Applicable: M5 (please complete the following information):**
0.3.22

**Comment by vicpylon** [comment]
No, I did not check that, but a few hours later it just appeared back on the web explorer.

**Comment by PavlosTze** [comment]
@vicpylon  As a final confirmation, can you please check both in the web and in-app what is the status indicator?

**Comment by PavlosTze** [comment]
I am closing this issue. In case this appears again, please re-open it or contact us. Thank you :)
